// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `Hello.jce'
// **********************************************************************

package com.qq.MTT
{
    public final class MYE
    {
        public static const EM_CAT:int = 0;
        public static const EM_DOG:int = 1;
        public static const EM_BIRD:int = 2;
        public static const EM_MAX_PET:int = 3;
    }
}
