// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttAdsReq.h"

@implementation MttAdsReq

@synthesize JV2_PROP_NM(o,0,iPosId);
@synthesize JV2_PROP_NM(o,1,iUpdateTime);
@synthesize JV2_PROP_NM(o,2,iNumber);
@synthesize JV2_PROP_NM(o,3,iQBType);

+ (void)initialize
{
    if (self == [MttAdsReq class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.AdsReq";
}

@end
