// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttBrokerSimplifiedPushRequest : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(requestType,setRequestType:)) JceInt8 JV2_PROP_NM(o,0,requestType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sGUID,setSGUID:)) NSData* JV2_PROP_NM(o,1,sGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(sQUA,setSQUA:)) NSString* JV2_PROP_NM(o,2,sQUA);
@property (nonatomic, retain, JV2_PROP_GS_V2(sLC,setSLC:)) NSString* JV2_PROP_NM(o,3,sLC);
@property (nonatomic, retain, JV2_PROP_GS_V2(sSession,setSSession:)) NSString* JV2_PROP_NM(o,4,sSession);
@property (nonatomic, assign, JV2_PROP_GS_V2(wTabId,setWTabId:)) JceInt16 JV2_PROP_NM(o,5,wTabId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sChannelId,setSChannelId:)) NSString* JV2_PROP_NM(o,6,sChannelId);
@property (nonatomic, retain, JV2_PROP_GS_V2(strCookie,setStrCookie:)) NSString* JV2_PROP_NM(o,11,strCookie);
@property (nonatomic, assign, JV2_PROP_GS_V2(iPushTime,setIPushTime:)) JceInt32 JV2_PROP_NM(r,12,iPushTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPushAppReqId,setVPushAppReqId:)) NSArray* JV2_PROP_EX(r,13,vPushAppReqId,VONSNumber);
@property (nonatomic, retain, JV2_PROP_GS_V2(vdata,setVdata:)) NSArray* JV2_PROP_EX(o,14,vdata,VONSData);
@property (nonatomic, assign, JV2_PROP_GS_V2(wVersion,setWVersion:)) JceInt16 JV2_PROP_NM(o,15,wVersion);
@property (nonatomic, assign, JV2_PROP_GS_V2(cFontSize,setCFontSize:)) JceInt8 JV2_PROP_NM(o,16,cFontSize);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,17,vCharSetKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenWidth,setWScreenWidth:)) JceInt16 JV2_PROP_NM(o,18,wScreenWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenHeight,setWScreenHeight:)) JceInt16 JV2_PROP_NM(o,19,wScreenHeight);

@end
