// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttBrokerFragResponse.h"

@implementation MttBrokerFragResponse

@synthesize JV2_PROP_NM(r,0,cReqType);
@synthesize JV2_PROP_NM(r,1,sUrl);
@synthesize JV2_PROP_NM(r,2,sFragKey);
@synthesize JV2_PROP_NM(r,3,cSeqNum);
@synthesize JV2_PROP_NM(r,4,iExpectOffset);
@synthesize JV2_PROP_NM(r,5,iRspContentLen);

+ (void)initialize
{
    if (self == [MttBrokerFragResponse class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sUrl) = DefaultJceString;
        JV2_PROP(sFragKey) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sUrl) = nil;
    JV2_PROP(sFragKey) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.BrokerFragResponse";
}

@end
