// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttBrokerPushResponse.h"
#import "MttBrokerSecurityResponse.h"

@interface MttBrokerTransferResponse : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sSession,setSSession:)) NSString* JV2_PROP_NM(r,0,sSession);
@property (nonatomic, assign, JV2_PROP_GS_V2(wTabId,setWTabId:)) JceInt16 JV2_PROP_NM(r,1,wTabId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPageEncodeName,setSPageEncodeName:)) NSString* JV2_PROP_NM(r,2,sPageEncodeName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cDirectWap,setCDirectWap:)) JceInt8 JV2_PROP_NM(r,3,cDirectWap);
@property (nonatomic, retain, JV2_PROP_GS_V2(sDirectWapUrl,setSDirectWapUrl:)) NSString* JV2_PROP_NM(r,4,sDirectWapUrl);
@property (nonatomic, assign, JV2_PROP_GS_V2(iContentTimeStamp,setIContentTimeStamp:)) JceInt32 JV2_PROP_NM(r,5,iContentTimeStamp);
@property (nonatomic, retain, JV2_PROP_GS_V2(sFragKey,setSFragKey:)) NSString* JV2_PROP_NM(r,6,sFragKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(iRspContentLen,setIRspContentLen:)) JceInt32 JV2_PROP_NM(r,7,iRspContentLen);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUserSession,setSUserSession:)) NSString* JV2_PROP_NM(o,8,sUserSession);
@property (nonatomic, retain, JV2_PROP_GS_V2(stPushResp,setStPushResp:)) MttBrokerPushResponse* JV2_PROP_NM(o,9,stPushResp);
@property (nonatomic, retain, JV2_PROP_GS_V2(stSecurityResp,setStSecurityResp:)) MttBrokerSecurityResponse* JV2_PROP_NM(o,10,stSecurityResp);
@property (nonatomic, assign, JV2_PROP_GS_V2(cShare,setCShare:)) JceInt8 JV2_PROP_NM(o,11,cShare);

@end
