// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttBrokerUserInfo.h"

@interface MttBrokerSecurityRequest : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUserInfo,setStUserInfo:)) MttBrokerUserInfo* JV2_PROP_NM(o,0,stUserInfo);
@property (nonatomic, assign, JV2_PROP_GS_V2(cType,setCType:)) JceInt8 JV2_PROP_NM(r,1,cType);
@property (nonatomic, retain, JV2_PROP_GS_V2(strUrl,setStrUrl:)) NSString* JV2_PROP_NM(o,2,strUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(strSha1,setStrSha1:)) NSString* JV2_PROP_NM(o,3,strSha1);

@end
