// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttBrowserVersion.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttBrowserVersionHelper

+ (NSString *)etos:(MttBrowserVersion)e
{
    switch(e){
        case MttBrowserVersion_OLDWAP1: return @"MttBrowserVersion_OLDWAP1";
        case MttBrowserVersion_OLDWAP2: return @"MttBrowserVersion_OLDWAP2";
        case MttBrowserVersion_NEWWAP1: return @"MttBrowserVersion_NEWWAP1";
        case MttBrowserVersion_NEWWAP2: return @"MttBrowserVersion_NEWWAP2";
        case MttBrowserVersion_HTML5: return @"MttBrowserVersion_HTML5";
        default: return @"";
    }
}

+ (MttBrowserVersion)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttBrowserVersion_OLDWAP1")) return MttBrowserVersion_OLDWAP1;
    if(isJceEnumStringEqual(s, @"MttBrowserVersion_OLDWAP2")) return MttBrowserVersion_OLDWAP2;
    if(isJceEnumStringEqual(s, @"MttBrowserVersion_NEWWAP1")) return MttBrowserVersion_NEWWAP1;
    if(isJceEnumStringEqual(s, @"MttBrowserVersion_NEWWAP2")) return MttBrowserVersion_NEWWAP2;
    if(isJceEnumStringEqual(s, @"MttBrowserVersion_HTML5")) return MttBrowserVersion_HTML5;
    return NSIntegerMin;
}

@end

#endif
