// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttBrokerSimplifiedRequest : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(requestType,setRequestType:)) JceInt8 JV2_PROP_NM(o,0,requestType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sGUID,setSGUID:)) NSData* JV2_PROP_NM(o,1,sGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(sQUA,setSQUA:)) NSString* JV2_PROP_NM(o,2,sQUA);
@property (nonatomic, retain, JV2_PROP_GS_V2(sLC,setSLC:)) NSString* JV2_PROP_NM(o,3,sLC);
@property (nonatomic, retain, JV2_PROP_GS_V2(sSession,setSSession:)) NSString* JV2_PROP_NM(o,4,sSession);
@property (nonatomic, assign, JV2_PROP_GS_V2(wTabId,setWTabId:)) JceInt16 JV2_PROP_NM(o,5,wTabId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sChannelId,setSChannelId:)) NSString* JV2_PROP_NM(o,6,sChannelId);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenWidth,setWScreenWidth:)) JceInt16 JV2_PROP_NM(o,10,wScreenWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenHeight,setWScreenHeight:)) JceInt16 JV2_PROP_NM(o,11,wScreenHeight);
@property (nonatomic, assign, JV2_PROP_GS_V2(cFontSize,setCFontSize:)) JceInt8 JV2_PROP_NM(o,12,cFontSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(cRowSpacing,setCRowSpacing:)) JceInt8 JV2_PROP_NM(o,13,cRowSpacing);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,14,vCharSetKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(cSupportedImage,setCSupportedImage:)) JceInt8 JV2_PROP_NM(o,15,cSupportedImage);
@property (nonatomic, assign, JV2_PROP_GS_V2(wVersion,setWVersion:)) JceInt16 JV2_PROP_NM(o,20,wVersion);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUrl,setSUrl:)) NSString* JV2_PROP_NM(o,21,sUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUserHttpHeader,setSUserHttpHeader:)) NSString* JV2_PROP_NM(o,22,sUserHttpHeader);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPageEncodeName,setSPageEncodeName:)) NSString* JV2_PROP_NM(o,23,sPageEncodeName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cZipType,setCZipType:)) JceInt8 JV2_PROP_NM(o,24,cZipType);
@property (nonatomic, assign, JV2_PROP_GS_V2(cImgQualityType,setCImgQualityType:)) JceInt8 JV2_PROP_NM(o,25,cImgQualityType);
@property (nonatomic, assign, JV2_PROP_GS_V2(wPageSizeKB,setWPageSizeKB:)) JceInt16 JV2_PROP_NM(o,26,wPageSizeKB);
@property (nonatomic, retain, JV2_PROP_GS_V2(vImgCacheFNV,setVImgCacheFNV:)) NSArray* JV2_PROP_EX(o,27,vImgCacheFNV,VONSNumber);
@property (nonatomic, assign, JV2_PROP_GS_V2(cLzmaDictOffset,setCLzmaDictOffset:)) JceInt8 JV2_PROP_NM(o,28,cLzmaDictOffset);
@property (nonatomic, assign, JV2_PROP_GS_V2(iEntry,setIEntry:)) JceInt32 JV2_PROP_NM(o,29,iEntry);
@property (nonatomic, assign, JV2_PROP_GS_V2(iEntryType,setIEntryType:)) JceInt32 JV2_PROP_NM(o,30,iEntryType);
@property (nonatomic, assign, JV2_PROP_GS_V2(cSecuritySwitch,setCSecuritySwitch:)) JceInt8 JV2_PROP_NM(o,31,cSecuritySwitch);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPostData,setVPostData:)) NSData* JV2_PROP_NM(o,40,vPostData);
@property (nonatomic, assign, JV2_PROP_GS_V2(cJSEvent,setCJSEvent:)) JceInt8 JV2_PROP_NM(o,41,cJSEvent);
@property (nonatomic, assign, JV2_PROP_GS_V2(iJSNode,setIJSNode:)) JceInt32 JV2_PROP_NM(o,42,iJSNode);
@property (nonatomic, retain, JV2_PROP_GS_V2(viKey,setViKey:)) NSArray* JV2_PROP_EX(o,43,viKey,VONSNumber);
@property (nonatomic, retain, JV2_PROP_GS_V2(vvbValue,setVvbValue:)) NSArray* JV2_PROP_EX(o,44,vvbValue,VONSData);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUpBoundary,setSUpBoundary:)) NSString* JV2_PROP_NM(o,50,sUpBoundary);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUpContentType,setSUpContentType:)) NSString* JV2_PROP_NM(o,51,sUpContentType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUpFileName,setSUpFileName:)) NSString* JV2_PROP_NM(o,52,sUpFileName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUpName,setSUpName:)) NSString* JV2_PROP_NM(o,53,sUpName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cUpZipType,setCUpZipType:)) JceInt8 JV2_PROP_NM(o,54,cUpZipType);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUpFileSize,setIUpFileSize:)) JceInt32 JV2_PROP_NM(o,55,iUpFileSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUpPackNo,setIUpPackNo:)) JceInt32 JV2_PROP_NM(o,56,iUpPackNo);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUpDataSize,setIUpDataSize:)) JceInt32 JV2_PROP_NM(o,57,iUpDataSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(cUpNeedResponse,setCUpNeedResponse:)) JceInt8 JV2_PROP_NM(o,58,cUpNeedResponse);
@property (nonatomic, assign, JV2_PROP_GS_V2(cStoreAbility,setCStoreAbility:)) JceInt8 JV2_PROP_NM(o,59,cStoreAbility);
@property (nonatomic, assign, JV2_PROP_GS_V2(iLanguageType,setILanguageType:)) JceInt32 JV2_PROP_NM(o,60,iLanguageType);
@property (nonatomic, assign, JV2_PROP_GS_V2(cContentType,setCContentType:)) JceInt8 JV2_PROP_NM(o,61,cContentType);
@property (nonatomic, assign, JV2_PROP_GS_V2(cReqEncrypted,setCReqEncrypted:)) JceInt8 JV2_PROP_NM(o,62,cReqEncrypted);

@end
