// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttBrokerDisplayInfo.h"

@implementation MttBrokerDisplayInfo

@synthesize JV2_PROP_NM(o,0,wScreenWidth);
@synthesize JV2_PROP_NM(o,1,wScreenHeight);
@synthesize JV2_PROP_NM(o,2,cFontSize);
@synthesize JV2_PROP_NM(o,3,cRowSpacing);
@synthesize JV2_PROP_NM(o,4,vCharSetKey);
@synthesize JV2_PROP_NM(o,5,cSupportedImage);

+ (void)initialize
{
    if (self == [MttBrokerDisplayInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(wScreenWidth) = 240;
        JV2_PROP(wScreenHeight) = 320;
        JV2_PROP(cFontSize) = 14;
        JV2_PROP(cRowSpacing) = 1;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vCharSetKey) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.BrokerDisplayInfo";
}

@end
