// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttBrokerSecurityRequest.h"

@implementation MttBrokerSecurityRequest

@synthesize JV2_PROP_NM(o,0,stUserInfo);
@synthesize JV2_PROP_NM(r,1,cType);
@synthesize JV2_PROP_NM(o,2,strUrl);
@synthesize JV2_PROP_NM(o,3,strSha1);

+ (void)initialize
{
    if (self == [MttBrokerSecurityRequest class]) {
        [MttBrokerUserInfo initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(strUrl) = DefaultJceString;
        JV2_PROP(strSha1) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUserInfo) = nil;
    JV2_PROP(strUrl) = nil;
    JV2_PROP(strSha1) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.BrokerSecurityRequest";
}

@end
