// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttContentEncoding_CONTENT_NORMAL,
    MttContentEncoding_CONTENT_GZIP
};
#define MttContentEncoding NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttContentEncodingHelper: JceEnumHelper

+ (NSString *)etos:(MttContentEncoding)e;
+ (MttContentEncoding)stoe:(NSString *)s;

@end

#endif
