// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttCityListRsp.h"

@implementation MttCityListRsp

@synthesize JV2_PROP_NM(o,0,sCityList);
@synthesize JV2_PROP_NM(o,1,iTime);

+ (void)initialize
{
    if (self == [MttCityListRsp class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sCityList) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sCityList) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.CityListRsp";
}

@end
