// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttConfirm.h"

@implementation MttConfirm

@synthesize JV2_PROP_NM(r,0,wVersion);
@synthesize JV2_PROP_NM(r,1,sSessionID);
@synthesize JV2_PROP_NM(r,2,iRequestID);
@synthesize JV2_PROP_NM(r,3,iExpectSequenceID);

+ (void)initialize
{
    if (self == [MttConfirm class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSessionID) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sSessionID) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.Confirm";
}

@end
