// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttHotWordsReq.h"
#import "MttUserBase.h"

@interface MttDynamicReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUB,setStUB:)) MttUserBase* JV2_PROP_NM(r,0,stUB);
@property (nonatomic, retain, JV2_PROP_GS_V2(stHotWordsReq,setStHotWordsReq:)) MttHotWordsReq* JV2_PROP_NM(r,1,stHotWordsReq);

@end
