// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttDynamicReq.h"

@implementation MttDynamicReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,stHotWordsReq);

+ (void)initialize
{
    if (self == [MttDynamicReq class]) {
        [MttHotWordsReq initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(stHotWordsReq) = [MttHotWordsReq object];
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(stHotWordsReq) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.DynamicReq";
}

@end
