// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttDynamicRsp.h"

@implementation MttDynamicRsp

@synthesize JV2_PROP_NM(r,0,stHotRsp);

+ (void)initialize
{
    if (self == [MttDynamicRsp class]) {
        [MttHotWordsRsp initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stHotRsp) = [MttHotWordsRsp object];
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stHotRsp) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.DynamicRsp";
}

@end
