// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttERelayProtoVer_PROTOCOL_VERSION_1,
    MttERelayProtoVer_PROTOCOL_VERSION_2
};
#define MttERelayProtoVer NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttERelayProtoVerHelper: JceEnumHelper

+ (NSString *)etos:(MttERelayProtoVer)e;
+ (MttERelayProtoVer)stoe:(NSString *)s;

@end

#endif
