// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttEPushServerType.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEPushServerTypeHelper

+ (NSString *)etos:(MttEPushServerType)e
{
    switch(e){
        case MttEPushServerType_PUSH_MSGBOX: return @"MttEPushServerType_PUSH_MSGBOX";
        case MttEPushServerType_PUSH_MB: return @"MttEPushServerType_PUSH_MB";
        case MttEPushServerType_PUSH_HOTWORD: return @"MttEPushServerType_PUSH_HOTWORD";
        case MttEPushServerType_PUSH_ADS: return @"MttEPushServerType_PUSH_ADS";
        case MttEPushServerType_PUSH_BANNER: return @"MttEPushServerType_PUSH_BANNER";
        case MttEPushServerType_PUSH_HOMELAND: return @"MttEPushServerType_PUSH_HOMELAND";
        case MttEPushServerType_PUSH_MAIL: return @"MttEPushServerType_PUSH_MAIL";
        case MttEPushServerType_PUSH_WEATHER: return @"MttEPushServerType_PUSH_WEATHER";
        default: return @"";
    }
}

+ (MttEPushServerType)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_MSGBOX")) return MttEPushServerType_PUSH_MSGBOX;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_MB")) return MttEPushServerType_PUSH_MB;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_HOTWORD")) return MttEPushServerType_PUSH_HOTWORD;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_ADS")) return MttEPushServerType_PUSH_ADS;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_BANNER")) return MttEPushServerType_PUSH_BANNER;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_HOMELAND")) return MttEPushServerType_PUSH_HOMELAND;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_MAIL")) return MttEPushServerType_PUSH_MAIL;
    if(isJceEnumStringEqual(s, @"MttEPushServerType_PUSH_WEATHER")) return MttEPushServerType_PUSH_WEATHER;
    return NSIntegerMin;
}

@end

#endif
