// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttEServerVer_AUTOSIZE = 2,
    MttEServerVer_NOKIAJAVA = 3,
    MttEServerVer_NOKIASYM = 4,
    MttEServerVer_NOKIASMBV5 = 5,
    MttEServerVer_LITE = 6,
    MttEServerVer_NOKIAITEM2 = 7,
    MttEServerVer_TELBREW = 8,
    MttEServerVer_TELANDROID = 9,
    MttEServerVer_IPAD = 10,
    MttEServerVer_IPAD2 = 11,
    MttEServerVer_UINCOM = 12,
    MttEServerVer_NOKIA = 13,
    MttEServerVer_JIGUANG = 14,
    MttEServerVer_GMCC = 15,
    MttEServerVer_APAD = 16,
    MttEServerVer_TELECOM = 17
};
#define MttEServerVer NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttEServerVerHelper: JceEnumHelper

+ (NSString *)etos:(MttEServerVer)e;
+ (MttEServerVer)stoe:(NSString *)s;

@end

#endif
