// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttEServerVer.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEServerVerHelper

+ (NSString *)etos:(MttEServerVer)e
{
    switch(e){
        case MttEServerVer_AUTOSIZE: return @"MttEServerVer_AUTOSIZE";
        case MttEServerVer_NOKIAJAVA: return @"MttEServerVer_NOKIAJAVA";
        case MttEServerVer_NOKIASYM: return @"MttEServerVer_NOKIASYM";
        case MttEServerVer_NOKIASMBV5: return @"MttEServerVer_NOKIASMBV5";
        case MttEServerVer_LITE: return @"MttEServerVer_LITE";
        case MttEServerVer_NOKIAITEM2: return @"MttEServerVer_NOKIAITEM2";
        case MttEServerVer_TELBREW: return @"MttEServerVer_TELBREW";
        case MttEServerVer_TELANDROID: return @"MttEServerVer_TELANDROID";
        case MttEServerVer_IPAD: return @"MttEServerVer_IPAD";
        case MttEServerVer_IPAD2: return @"MttEServerVer_IPAD2";
        case MttEServerVer_UINCOM: return @"MttEServerVer_UINCOM";
        case MttEServerVer_NOKIA: return @"MttEServerVer_NOKIA";
        case MttEServerVer_JIGUANG: return @"MttEServerVer_JIGUANG";
        case MttEServerVer_GMCC: return @"MttEServerVer_GMCC";
        case MttEServerVer_APAD: return @"MttEServerVer_APAD";
        case MttEServerVer_TELECOM: return @"MttEServerVer_TELECOM";
        default: return @"";
    }
}

+ (MttEServerVer)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttEServerVer_AUTOSIZE")) return MttEServerVer_AUTOSIZE;
    if(isJceEnumStringEqual(s, @"MttEServerVer_NOKIAJAVA")) return MttEServerVer_NOKIAJAVA;
    if(isJceEnumStringEqual(s, @"MttEServerVer_NOKIASYM")) return MttEServerVer_NOKIASYM;
    if(isJceEnumStringEqual(s, @"MttEServerVer_NOKIASMBV5")) return MttEServerVer_NOKIASMBV5;
    if(isJceEnumStringEqual(s, @"MttEServerVer_LITE")) return MttEServerVer_LITE;
    if(isJceEnumStringEqual(s, @"MttEServerVer_NOKIAITEM2")) return MttEServerVer_NOKIAITEM2;
    if(isJceEnumStringEqual(s, @"MttEServerVer_TELBREW")) return MttEServerVer_TELBREW;
    if(isJceEnumStringEqual(s, @"MttEServerVer_TELANDROID")) return MttEServerVer_TELANDROID;
    if(isJceEnumStringEqual(s, @"MttEServerVer_IPAD")) return MttEServerVer_IPAD;
    if(isJceEnumStringEqual(s, @"MttEServerVer_IPAD2")) return MttEServerVer_IPAD2;
    if(isJceEnumStringEqual(s, @"MttEServerVer_UINCOM")) return MttEServerVer_UINCOM;
    if(isJceEnumStringEqual(s, @"MttEServerVer_NOKIA")) return MttEServerVer_NOKIA;
    if(isJceEnumStringEqual(s, @"MttEServerVer_JIGUANG")) return MttEServerVer_JIGUANG;
    if(isJceEnumStringEqual(s, @"MttEServerVer_GMCC")) return MttEServerVer_GMCC;
    if(isJceEnumStringEqual(s, @"MttEServerVer_APAD")) return MttEServerVer_APAD;
    if(isJceEnumStringEqual(s, @"MttEServerVer_TELECOM")) return MttEServerVer_TELECOM;
    return NSIntegerMin;
}

@end

#endif
