// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttETPV.h"

@implementation MttETPV

@synthesize JV2_PROP_NM(r,0,sURL);
@synthesize JV2_PROP_EX(r,1,stURLPV,VOMTTURLPV);

+ (void)initialize
{
    if (self == [MttETPV class]) {
        [MttURLPV initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sURL) = DefaultJceString;
        JV2_PROP(stURLPV) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sURL) = nil;
    JV2_PROP(stURLPV) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.ETPV";
}

@end
