// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttHotWordInfo.h"

@implementation MttHotWordInfo

@synthesize JV2_PROP_NM(o,0,sHotWordName);
@synthesize JV2_PROP_NM(o,1,sHotWordUrl);
@synthesize JV2_PROP_NM(o,2,iHotType);

+ (void)initialize
{
    if (self == [MttHotWordInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sHotWordName) = DefaultJceString;
        JV2_PROP(sHotWordUrl) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sHotWordName) = nil;
    JV2_PROP(sHotWordUrl) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.HotWordInfo";
}

@end
