// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttHotListReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sMd5,setSMd5:)) NSString* JV2_PROP_NM(o,0,sMd5);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHotType,setIHotType:)) JceInt32 JV2_PROP_NM(o,1,iHotType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sQua,setSQua:)) NSString* JV2_PROP_NM(o,2,sQua);

@end
