// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttIPListRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vQProxyList,setVQProxyList:)) NSArray* JV2_PROP_EX(o,0,vQProxyList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vProxyList,setVProxyList:)) NSArray* JV2_PROP_EX(o,1,vProxyList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vRelayList,setVRelayList:)) NSArray* JV2_PROP_EX(o,2,vRelayList,VONSString);

@end
