// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttIconInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iIconId,setIIconId:)) JceInt32 JV2_PROP_NM(r,0,iIconId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sIconName,setSIconName:)) NSString* JV2_PROP_NM(r,1,sIconName);
@property (nonatomic, retain, JV2_PROP_GS_V2(vIconData,setVIconData:)) NSData* JV2_PROP_NM(r,2,vIconData);

@end
