// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttPluginVersion : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sType,setSType:)) NSString* JV2_PROP_NM(r,0,sType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sVersion,setSVersion:)) NSString* JV2_PROP_NM(o,1,sVersion);
@property (nonatomic, retain, JV2_PROP_GS_V2(mSpecCond,setMSpecCond:)) NSDictionary* JV2_PROP_EX(o,2,mSpecCond,M09ONSStringONSString);

@end
