// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPicInfo.h"

@implementation MttPicInfo

@synthesize JV2_PROP_NM(r,0,sFileName);
@synthesize JV2_PROP_NM(r,1,vPicData);

+ (void)initialize
{
    if (self == [MttPicInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sFileName) = DefaultJceString;
        JV2_PROP(vPicData) = DefaultJceData;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sFileName) = nil;
    JV2_PROP(vPicData) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PicInfo";
}

@end
