// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttPageBrowserReq : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(version,setVersion:)) JceInt32 JV2_PROP_NM(r,0,version);
@property (nonatomic, assign, JV2_PROP_GS_V2(size,setSize:)) JceInt8 JV2_PROP_NM(r,1,size);
@property (nonatomic, retain, JV2_PROP_GS_V2(lastVersionMD5,setLastVersionMD5:)) NSString* JV2_PROP_NM(r,2,lastVersionMD5);
@property (nonatomic, assign, JV2_PROP_GS_V2(special,setSpecial:)) JceInt32 JV2_PROP_NM(o,3,special);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWidth,setIWidth:)) JceInt32 JV2_PROP_NM(o,4,iWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHeight,setIHeight:)) JceInt32 JV2_PROP_NM(o,5,iHeight);
@property (nonatomic, assign, JV2_PROP_GS_V2(iFontSize,setIFontSize:)) JceInt32 JV2_PROP_NM(o,6,iFontSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(iRowSpacing,setIRowSpacing:)) JceInt32 JV2_PROP_NM(o,7,iRowSpacing);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,8,vCharSetKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(wVersion,setWVersion:)) JceInt16 JV2_PROP_NM(o,9,wVersion);
@property (nonatomic, assign, JV2_PROP_GS_V2(iNaviTime,setINaviTime:)) JceInt32 JV2_PROP_NM(o,10,iNaviTime);

@end
