// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPageRsp.h"

@implementation MttPageRsp

@synthesize JV2_PROP_NM(r,0,pageId);
@synthesize JV2_PROP_NM(r,1,updateAll);
@synthesize JV2_PROP_NM(r,2,lastUpdateTime);
@synthesize JV2_PROP_NM(r,3,top);
@synthesize JV2_PROP_NM(r,4,foot);
@synthesize JV2_PROP_EX(r,5,items,VOMTTItemRsp);

+ (void)initialize
{
    if (self == [MttPageRsp class]) {
        [MttItemRsp initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(top) = DefaultJceString;
        JV2_PROP(foot) = DefaultJceString;
        JV2_PROP(items) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(top) = nil;
    JV2_PROP(foot) = nil;
    JV2_PROP(items) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PageRsp";
}

@end
