// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPluginRspNew.h"

@implementation MttPluginRspNew

@synthesize JV2_PROP_EX(r,0,vPlugins,VOMTTPluginInfoNew);

+ (void)initialize
{
    if (self == [MttPluginRspNew class]) {
        [MttPluginInfoNew initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vPlugins) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vPlugins) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PluginRspNew";
}

@end
