// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPageBrowserRsp.h"

@implementation MttPageBrowserRsp

@synthesize JV2_PROP_NM(r,0,resultCode);
@synthesize JV2_PROP_NM(r,1,lastVersionMD5);
@synthesize JV2_PROP_NM(r,2,content);
@synthesize JV2_PROP_NM(o,3,vLiteContent);
@synthesize JV2_PROP_NM(o,4,naviRsp);

+ (void)initialize
{
    if (self == [MttPageBrowserRsp class]) {
        [MttNaviRsp initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(lastVersionMD5) = DefaultJceString;
        JV2_PROP(content) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(lastVersionMD5) = nil;
    JV2_PROP(content) = nil;
    JV2_PROP(vLiteContent) = nil;
    JV2_PROP(naviRsp) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PageBrowserRsp";
}

@end
