// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttRequest.h"

@implementation MttRequest

@synthesize JV2_PROP_NM(r,0,wVersion);
@synthesize JV2_PROP_NM(r,1,sSessionID);
@synthesize JV2_PROP_NM(r,2,wTabID);
@synthesize JV2_PROP_NM(r,3,iRequestID);
@synthesize JV2_PROP_NM(r,4,iSequenceID);
@synthesize JV2_PROP_NM(r,5,cFinishFlag);
@synthesize JV2_PROP_NM(r,6,eContentEncoding);
@synthesize JV2_PROP_NM(r,7,eAcceptEncoding);
@synthesize JV2_PROP_NM(r,8,iRspMaxPacketSize);

+ (void)initialize
{
    if (self == [MttRequest class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSessionID) = DefaultJceString;
        JV2_PROP(iSequenceID) = 1;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sSessionID) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.Request";
}

@end
