// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttDirectPolicy.h"

@interface MttRelayPageRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iPageSize,setIPageSize:)) JceInt32 JV2_PROP_NM(r,0,iPageSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(eDirectPolicy,setEDirectPolicy:)) MttDirectPolicy JV2_PROP_NM(r,1,eDirectPolicy);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPageOrigEncode,setSPageOrigEncode:)) NSString* JV2_PROP_NM(r,2,sPageOrigEncode);
@property (nonatomic, retain, JV2_PROP_GS_V2(sDirectDomain,setSDirectDomain:)) NSString* JV2_PROP_NM(o,3,sDirectDomain);

@end
