// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSoftAnalyseInfo.h"

@implementation MttSoftAnalyseInfo

@synthesize JV2_PROP_NM(r,0,safeTypeID);
@synthesize JV2_PROP_NM(r,1,safeTypeDesc);
@synthesize JV2_PROP_NM(r,2,checkAdvise);
@synthesize JV2_PROP_NM(r,3,checkDesc);
@synthesize JV2_PROP_NM(o,4,softSha1);
@synthesize JV2_PROP_NM(o,5,analyseState);

+ (void)initialize
{
    if (self == [MttSoftAnalyseInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(safeTypeDesc) = DefaultJceString;
        JV2_PROP(checkAdvise) = DefaultJceString;
        JV2_PROP(checkDesc) = DefaultJceString;
        JV2_PROP(softSha1) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(safeTypeDesc) = nil;
    JV2_PROP(checkAdvise) = nil;
    JV2_PROP(checkDesc) = nil;
    JV2_PROP(softSha1) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.SoftAnalyseInfo";
}

@end
