// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttSearchInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sShortName,setSShortName:)) NSString* JV2_PROP_NM(r,0,sShortName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sAllName,setSAllName:)) NSString* JV2_PROP_NM(r,1,sAllName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sHref,setSHref:)) NSString* JV2_PROP_NM(r,2,sHref);
@property (nonatomic, retain, JV2_PROP_GS_V2(sImageName,setSImageName:)) NSString* JV2_PROP_NM(r,3,sImageName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sEncodeType,setSEncodeType:)) NSString* JV2_PROP_NM(r,4,sEncodeType);
@property (nonatomic, assign, JV2_PROP_GS_V2(iDefault,setIDefault:)) JceInt32 JV2_PROP_NM(o,5,iDefault);
@property (nonatomic, retain, JV2_PROP_GS_V2(sSearchName,setSSearchName:)) NSString* JV2_PROP_NM(o,6,sSearchName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sImageData,setSImageData:)) NSData* JV2_PROP_NM(o,7,sImageData);

@end
