// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSearchRsp.h"

@implementation MttSearchRsp

@synthesize JV2_PROP_NM(r,0,resultCode);
@synthesize JV2_PROP_EX(r,1,vSearchInfo,VOMTTSearchInfo);
@synthesize JV2_PROP_EX(r,2,imageRes,VOMTTIcon);
@synthesize JV2_PROP_NM(r,3,iSearchTime);

+ (void)initialize
{
    if (self == [MttSearchRsp class]) {
        [MttIcon initialize];
        [MttSearchInfo initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vSearchInfo) = DefaultJceArray;
        JV2_PROP(imageRes) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vSearchInfo) = nil;
    JV2_PROP(imageRes) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.SearchRsp";
}

@end
