// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttIcon.h"
#import "MttSearchTypeInfo.h"

@interface MttSearchTypeRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(resultCode,setResultCode:)) JceInt8 JV2_PROP_NM(o,0,resultCode);
@property (nonatomic, retain, JV2_PROP_GS_V2(vSearchTypeInfo,setVSearchTypeInfo:)) NSArray* JV2_PROP_EX(o,1,vSearchTypeInfo,VOMTTSearchTypeInfo);
@property (nonatomic, retain, JV2_PROP_GS_V2(imageRes,setImageRes:)) NSArray* JV2_PROP_EX(o,2,imageRes,VOMTTIcon);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSearchTypeTime,setISearchTypeTime:)) JceInt32 JV2_PROP_NM(o,3,iSearchTypeTime);

@end
