// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttSplashRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vPicData,setVPicData:)) NSData* JV2_PROP_NM(r,0,vPicData);
@property (nonatomic, assign, JV2_PROP_GS_V2(iEffectTime,setIEffectTime:)) JceInt32 JV2_PROP_NM(r,1,iEffectTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iInvalidTime,setIInvalidTime:)) JceInt32 JV2_PROP_NM(r,2,iInvalidTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iShowSecond,setIShowSecond:)) JceInt8 JV2_PROP_NM(r,3,iShowSecond);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPicMd5,setSPicMd5:)) NSString* JV2_PROP_NM(r,4,sPicMd5);
@property (nonatomic, retain, JV2_PROP_GS_V2(sCondMd5,setSCondMd5:)) NSString* JV2_PROP_NM(r,5,sCondMd5);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSplashType,setISplashType:)) JceInt8 JV2_PROP_NM(o,6,iSplashType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPicUrl,setSPicUrl:)) NSString* JV2_PROP_NM(o,7,sPicUrl);

@end
