// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttThirdUse.h"

@implementation MttThirdUse

@synthesize JV2_PROP_NM(r,0,sPID);
@synthesize JV2_PROP_NM(r,1,eEUSESTAT);
@synthesize JV2_PROP_NM(r,2,sUrl);
@synthesize JV2_PROP_NM(r,3,iSucc);
@synthesize JV2_PROP_NM(r,4,iFail);

+ (void)initialize
{
    if (self == [MttThirdUse class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sPID) = DefaultJceString;
        JV2_PROP(sUrl) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sPID) = nil;
    JV2_PROP(sUrl) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.ThirdUse";
}

@end
