// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttWeatherReq : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iDayIndex,setIDayIndex:)) JceInt32 JV2_PROP_NM(o,0,iDayIndex);
@property (nonatomic, assign, JV2_PROP_GS_V2(iDayCount,setIDayCount:)) JceInt32 JV2_PROP_NM(o,1,iDayCount);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUpdateTime,setIUpdateTime:)) JceInt32 JV2_PROP_NM(o,2,iUpdateTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(sCityName,setSCityName:)) NSString* JV2_PROP_NM(o,3,sCityName);

@end
