
TOPDIR  := ../..
include ${TOPDIR}/make.rules

#-------------------------------------------------------------------------------

INCLUDE   += -I${TOPDIR}/include/servant
LIB       += ${TAFLIB}

#-------------------------------------------------------------------------------

TARGET  := ${NODEBIN}

#-------------------------------------------------------------------------------

include ${TOPDIR}/jce/node/Node.mk
include ${TOPDIR}/jce/registry/Registry.mk
include ${TOPDIR}/inc.mk
