// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public final class StatQueryPrxHelper extends com.qq.taf.proxy.ServantProxy implements StatQueryPrx
{

    public StatQueryPrxHelper taf_hash(int hashCode)
    {
        super.taf_hash(hashCode);
        return this;
    }

    public java.util.Map __defaultContext()
    {
        java.util.HashMap _ctx = new java.util.HashMap();
        return _ctx;
    }

    protected String sServerEncoding = "GBK";
    public int setServerEncoding(String se){
        sServerEncoding = se;
        return 0;
    }

    public int query(com.qq.taf.StatQueryKey tKey, boolean bMaster, com.qq.taf.StatQueryValueHolder tValue)
    {
        return query(tKey, bMaster, tValue, __defaultContext());
    }

    @SuppressWarnings("unchecked")
    public int query(com.qq.taf.StatQueryKey tKey, boolean bMaster, com.qq.taf.StatQueryValueHolder tValue, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(tKey, 1);
        _os.write(bMaster, 2);
        if(tValue.value != null)         _os.write(tValue.value, 3);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        byte[] _returnSBuffer = taf_invoke("query", _sBuffer, __ctx, _mStatus);

        com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(_returnSBuffer);
        _is.setServerEncoding(sServerEncoding);
        int _ret = 0;
        _ret = (int) _is.read(_ret, 0, true);
        tValue.value = new com.qq.taf.StatQueryValue();
        tValue.value = (com.qq.taf.StatQueryValue) _is.read(tValue.value, 3, true);
        return _ret;
    }

    public void async_query(com.qq.taf.StatQueryPrxCallback callback, com.qq.taf.StatQueryKey tKey, boolean bMaster)
    {
        async_query(callback, tKey, bMaster, __defaultContext());
    }

    public void async_query(com.qq.taf.StatQueryPrxCallback callback, com.qq.taf.StatQueryKey tKey, boolean bMaster, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(tKey, 1);
        _os.write(bMaster, 2);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        taf_invokeAsync(callback, "query", _sBuffer, __ctx, _mStatus);

    }

    public int queryDbInf(String sModule, com.qq.taf.DbHolder tDb)
    {
        return queryDbInf(sModule, tDb, __defaultContext());
    }

    @SuppressWarnings("unchecked")
    public int queryDbInf(String sModule, com.qq.taf.DbHolder tDb, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(sModule, 1);
        if(tDb.value != null)         _os.write(tDb.value, 2);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        byte[] _returnSBuffer = taf_invoke("queryDbInf", _sBuffer, __ctx, _mStatus);

        com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(_returnSBuffer);
        _is.setServerEncoding(sServerEncoding);
        int _ret = 0;
        _ret = (int) _is.read(_ret, 0, true);
        tDb.value = new com.qq.taf.Db();
        tDb.value = (com.qq.taf.Db) _is.read(tDb.value, 2, true);
        return _ret;
    }

    public void async_queryDbInf(com.qq.taf.StatQueryPrxCallback callback, String sModule)
    {
        async_queryDbInf(callback, sModule, __defaultContext());
    }

    public void async_queryDbInf(com.qq.taf.StatQueryPrxCallback callback, String sModule, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(sModule, 1);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        taf_invokeAsync(callback, "queryDbInf", _sBuffer, __ctx, _mStatus);

    }

}
