// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public final class StatQueryValueHolder
{
    public StatQueryValueHolder()
    {
    }
    public StatQueryValueHolder(StatQueryValue value)
    {
        this.value = value;
    }

    public StatQueryValue value;
}
