// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public final class StatQueryKey extends com.qq.taf.jce.JceStruct implements Comparable<StatQueryKey>, java.lang.Cloneable
{
    public String className()
    {
        return "taf.StatQueryKey";
    }

    public String fullClassName()
    {
        return "com.qq.taf.StatQueryKey";
    }

    public String name = "";

    public String ip = "";

    public int page = 0;

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getIp()
    {
        return ip;
    }

    public void  setIp(String ip)
    {
        this.ip = ip;
    }

    public int getPage()
    {
        return page;
    }

    public void  setPage(int page)
    {
        this.page = page;
    }

    public StatQueryKey()
    {
        setName(name);
        setIp(ip);
        setPage(page);
    }

    public StatQueryKey(String name, String ip, int page)
    {
        setName(name);
        setIp(ip);
        setPage(page);
    }

    public int compareTo(StatQueryKey o)
    {
        int[] r = 
        {
            com.qq.taf.jce.JceUtil.compareTo(name, o.name), 
            com.qq.taf.jce.JceUtil.compareTo(ip, o.ip), 
            com.qq.taf.jce.JceUtil.compareTo(page, o.page)
        };
        for(int i = 0; i < r.length; ++i)
        {
            if(r[i] != 0) return r[i];
        }
        return 0;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        StatQueryKey t = (StatQueryKey) o;
        return (
            com.qq.taf.jce.JceUtil.equals(name, t.name) && 
            com.qq.taf.jce.JceUtil.equals(ip, t.ip) && 
            com.qq.taf.jce.JceUtil.equals(page, t.page) );
    }

    public int hashCode()
    {
        int [] hc = { 
            com.qq.taf.jce.JceUtil.hashCode(name), 
            com.qq.taf.jce.JceUtil.hashCode(ip), 
            com.qq.taf.jce.JceUtil.hashCode(page)
        };
        return java.util.Arrays.hashCode(hc);
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(name, 0);
        _os.write(ip, 1);
        _os.write(page, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setName( _is.readString(0, true));

        setIp( _is.readString(1, true));

        setPage((int) _is.read(page, 2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(name, "name");
        _ds.display(ip, "ip");
        _ds.display(page, "page");
    }

}

