// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public final class StatQueryKeyHolder
{
    public StatQueryKeyHolder()
    {
    }
    public StatQueryKeyHolder(StatQueryKey value)
    {
        this.value = value;
    }

    public StatQueryKey value;
}
