// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public final class StatQueryValue extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "taf.StatQueryValue";
    }

    public String fullClassName()
    {
        return "com.qq.taf.StatQueryValue";
    }

    public int nextpage = 0;

    public java.util.ArrayList<com.qq.taf.StatQueryData> dataList = null;

    public int getNextpage()
    {
        return nextpage;
    }

    public void  setNextpage(int nextpage)
    {
        this.nextpage = nextpage;
    }

    public java.util.ArrayList<com.qq.taf.StatQueryData> getDataList()
    {
        return dataList;
    }

    public void  setDataList(java.util.ArrayList<com.qq.taf.StatQueryData> dataList)
    {
        this.dataList = dataList;
    }

    public StatQueryValue()
    {
        setNextpage(nextpage);
        setDataList(dataList);
    }

    public StatQueryValue(int nextpage, java.util.ArrayList<com.qq.taf.StatQueryData> dataList)
    {
        setNextpage(nextpage);
        setDataList(dataList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        StatQueryValue t = (StatQueryValue) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nextpage, t.nextpage) && 
            com.qq.taf.jce.JceUtil.equals(dataList, t.dataList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nextpage, 0);
        _os.write(dataList, 1);
    }

    static java.util.ArrayList<com.qq.taf.StatQueryData> cache_dataList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setNextpage((int) _is.read(nextpage, 0, true));

        if(null == cache_dataList)
        {
            cache_dataList = new java.util.ArrayList<com.qq.taf.StatQueryData>();
            com.qq.taf.StatQueryData __var_1 = new com.qq.taf.StatQueryData();
            ((java.util.ArrayList<com.qq.taf.StatQueryData>)cache_dataList).add(__var_1);
        }
        setDataList((java.util.ArrayList<com.qq.taf.StatQueryData>) _is.read(cache_dataList, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(nextpage, "nextpage");
        _ds.display(dataList, "dataList");
    }

}

