// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `StatQuery.jce'
// **********************************************************************

package com.qq.taf;

public abstract class StatQueryPrxCallback extends com.qq.taf.proxy.ServantProxyCallback
{
    protected String __taf__StatQuery_all[] = 
    {
        "query",
        "queryDbInf"
    };

    protected String sServerEncoding = "GBK";
    public int setServerEncoding(String se){
        sServerEncoding = se;
        return 0;
    }

    public abstract void callback_query(int _ret, com.qq.taf.StatQueryValue tValue);

    public abstract void callback_query_exception(int _iRet);

    public abstract void callback_queryDbInf(int _ret, com.qq.taf.Db tDb);

    public abstract void callback_queryDbInf_exception(int _iRet);

    final public int _onDispatch(String sFuncName, com.qq.taf.ResponsePacket response)
    {

        int iPos = java.util.Arrays.binarySearch(__taf__StatQuery_all, sFuncName);
        if(iPos < 0 || iPos >= 2) return -1; //or throw execption?
        switch(iPos)
        {
            case 0:
            {
                if ( response.iRet != com.qq.taf.cnst.JCESERVERSUCCESS.value )
                {
                    callback_query_exception(response.iRet);
                    return response.iRet;
                }
                com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(response.sBuffer);
                _is.setServerEncoding(sServerEncoding);
                int _ret = 0;
                _ret = (int) _is.read(_ret, 0, true);

                com.qq.taf.StatQueryValue tValue = new com.qq.taf.StatQueryValue();
                tValue = (com.qq.taf.StatQueryValue) _is.read(tValue, 3, true);

                callback_query(_ret, tValue);
                break;
            }
            case 1:
            {
                if ( response.iRet != com.qq.taf.cnst.JCESERVERSUCCESS.value )
                {
                    callback_queryDbInf_exception(response.iRet);
                    return response.iRet;
                }
                com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(response.sBuffer);
                _is.setServerEncoding(sServerEncoding);
                int _ret = 0;
                _ret = (int) _is.read(_ret, 0, true);

                com.qq.taf.Db tDb = new com.qq.taf.Db();
                tDb = (com.qq.taf.Db) _is.read(tDb, 2, true);

                callback_queryDbInf(_ret, tDb);
                break;
            }
        }
        return 0;
    }
}
