
#-----------------------------------------------------------------------

APP       := Test
TARGET    := queryStatClient
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= --with-taf

LIB       += -L/usr/local/mysql/lib/mysql -lmysqlclient
#-----------------------------------------------------------------------

include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
