// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.2.0 by WSRD Tencent.
// Generated from `UserInfo.jce'
// **********************************************************************

package com.qq.jce.wup.test;

public final class UserInfoHolder
{
    public UserInfoHolder()
    {
    }
    public UserInfoHolder(UserInfo value)
    {
        this.value = value;
    }

    public UserInfo value;
}
