
#-----------------------------------------------------------------------

APP       := QUAN
TARGET    := PostServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

#-----------------------------------------------------------------------

include /home/tafjce/QUAN/UserInfoServer/UserInfoServer.mk
include /home/tafjce/QUAN/SecretServer/SecretServer.mk
include /home/tafjce/Comm/KeywordServer/KeywordServer.mk
include /home/tafjce/Comm/ErrorCode/ErrorCode.mk
include /home/zhengqiao/Util/AutoLog/AutoLog.mk
include /usr/local/taf/makefile.taf
LIB       += -lmysqlclient -lz

#-----------------------------------------------------------------------
