// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.7 by WSRD Tencent.
// Generated from `TafCaseServant.jce'
// **********************************************************************

package com.qq.java.testcase.testcaseservant;

public interface TafCaseServantPrx
{
    public int getUser(com.qq.java.testcase.testcaseservant.UserInfo inUser, com.qq.java.testcase.testcaseservant.UserInfoHolder outUser);

    public int getUser(com.qq.java.testcase.testcaseservant.UserInfo inUser, com.qq.java.testcase.testcaseservant.UserInfoHolder outUser, java.util.Map __ctx);

    public void async_getUser(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback, com.qq.java.testcase.testcaseservant.UserInfo inUser);

    public void async_getUser(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback, com.qq.java.testcase.testcaseservant.UserInfo inUser, java.util.Map __ctx);


    public int test();

    public int test(java.util.Map __ctx);

    public void async_test(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback);

    public void async_test(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback, java.util.Map __ctx);


    public int testUnsigned(short ubInUin, int usInUin, long uiInUin, com.qq.taf.holder.JceShortHolder ubOutUin, com.qq.taf.holder.JceIntHolder usOutUin, com.qq.taf.holder.JceLongHolder uiOutUin);

    public int testUnsigned(short ubInUin, int usInUin, long uiInUin, com.qq.taf.holder.JceShortHolder ubOutUin, com.qq.taf.holder.JceIntHolder usOutUin, com.qq.taf.holder.JceLongHolder uiOutUin, java.util.Map __ctx);

    public void async_testUnsigned(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback, short ubInUin, int usInUin, long uiInUin);

    public void async_testUnsigned(com.qq.java.testcase.testcaseservant.TafCaseServantPrxCallback callback, short ubInUin, int usInUin, long uiInUin, java.util.Map __ctx);


}
