// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

package com.duowan.QUAN;

public final class UserId extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "QUAN.UserId";
    }

    public String fullClassName()
    {
        return "com.duowan.QUAN.UserId";
    }

    public String sUA = "";

    public byte [] vGuid = null;

    public long lUId = 0;

    public String sToken = "";

    public String getSUA()
    {
        return sUA;
    }

    public void  setSUA(String sUA)
    {
        this.sUA = sUA;
    }

    public byte [] getVGuid()
    {
        return vGuid;
    }

    public void  setVGuid(byte [] vGuid)
    {
        this.vGuid = vGuid;
    }

    public long getLUId()
    {
        return lUId;
    }

    public void  setLUId(long lUId)
    {
        this.lUId = lUId;
    }

    public String getSToken()
    {
        return sToken;
    }

    public void  setSToken(String sToken)
    {
        this.sToken = sToken;
    }

    public UserId()
    {
        setSUA(sUA);
        setVGuid(vGuid);
        setLUId(lUId);
        setSToken(sToken);
    }

    public UserId(String sUA, byte [] vGuid, long lUId, String sToken)
    {
        setSUA(sUA);
        setVGuid(vGuid);
        setLUId(lUId);
        setSToken(sToken);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UserId t = (UserId) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(sUA, t.sUA) && 
            com.duowan.taf.jce.JceUtil.equals(vGuid, t.vGuid) && 
            com.duowan.taf.jce.JceUtil.equals(lUId, t.lUId) && 
            com.duowan.taf.jce.JceUtil.equals(sToken, t.sToken) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != sUA)
        {
            _os.write(sUA, 0);
        }
        if (null != vGuid)
        {
            _os.write(vGuid, 1);
        }
        _os.write(lUId, 2);
        if (null != sToken)
        {
            _os.write(sToken, 3);
        }
    }

    static byte [] cache_vGuid;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setSUA( _is.readString(0, false));

        if(null == cache_vGuid)
        {
            cache_vGuid = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vGuid)[0] = __var_1;
        }
        setVGuid((byte []) _is.read(cache_vGuid, 1, false));

        setLUId((long) _is.read(lUId, 2, false));

        setSToken( _is.readString(3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sUA, "sUA");
        _ds.display(vGuid, "vGuid");
        _ds.display(lUId, "lUId");
        _ds.display(sToken, "sToken");
    }

}

