// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `Notify.jce'
// **********************************************************************

package com.qq.taf.server.jce2java;

public final class NotifyInfoHolder
{
    public NotifyInfoHolder()
    {
    }
    public NotifyInfoHolder(NotifyInfo value)
    {
        this.value = value;
    }

    public NotifyInfo value;
}
