// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.1.7 by WSRD Tencent.
// Generated from `NodeF.jce'
// **********************************************************************

package com.qq.taf.server.jce2java;

public interface ServerFPrx
{
    public int keepAlive(com.qq.taf.server.jce2java.ServerInfo serverInfo);

    public int keepAlive(com.qq.taf.server.jce2java.ServerInfo serverInfo, java.util.Map __ctx);

    public void async_keepAlive(com.qq.taf.server.jce2java.ServerFPrxCallback callback, com.qq.taf.server.jce2java.ServerInfo serverInfo);

    public void async_keepAlive(com.qq.taf.server.jce2java.ServerFPrxCallback callback, com.qq.taf.server.jce2java.ServerInfo serverInfo, java.util.Map __ctx);


    public int reportVersion(String app, String serverName, String version);

    public int reportVersion(String app, String serverName, String version, java.util.Map __ctx);

    public void async_reportVersion(com.qq.taf.server.jce2java.ServerFPrxCallback callback, String app, String serverName, String version);

    public void async_reportVersion(com.qq.taf.server.jce2java.ServerFPrxCallback callback, String app, String serverName, String version, java.util.Map __ctx);


}
