// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `Notify.jce'
// **********************************************************************

package com.qq.taf.server.proxy;

public interface NotifyPrx
{
    public int getNotifyInfo(com.qq.taf.server.proxy.NotifyKey stKey, com.qq.taf.server.proxy.NotifyInfoHolder stInfo);

    public int getNotifyInfo(com.qq.taf.server.proxy.NotifyKey stKey, com.qq.taf.server.proxy.NotifyInfoHolder stInfo, java.util.Map __ctx);

    public void async_getNotifyInfo(com.qq.taf.server.proxy.NotifyPrxCallback callback, com.qq.taf.server.proxy.NotifyKey stKey);

    public void async_getNotifyInfo(com.qq.taf.server.proxy.NotifyPrxCallback callback, com.qq.taf.server.proxy.NotifyKey stKey, java.util.Map __ctx);


    public void notifyServer(String sServerName, int level, String sMessage);

    public void notifyServer(String sServerName, int level, String sMessage, java.util.Map __ctx);

    public void async_notifyServer(com.qq.taf.server.proxy.NotifyPrxCallback callback, String sServerName, int level, String sMessage);

    public void async_notifyServer(com.qq.taf.server.proxy.NotifyPrxCallback callback, String sServerName, int level, String sMessage, java.util.Map __ctx);


    public void reportServer(String sServerName, String sThreadId, String sMessage);

    public void reportServer(String sServerName, String sThreadId, String sMessage, java.util.Map __ctx);

    public void async_reportServer(com.qq.taf.server.proxy.NotifyPrxCallback callback, String sServerName, String sThreadId, String sMessage);

    public void async_reportServer(com.qq.taf.server.proxy.NotifyPrxCallback callback, String sServerName, String sThreadId, String sMessage, java.util.Map __ctx);


}
