// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `Notify.jce'
// **********************************************************************

package com.qq.taf.server.proxy;

public final class NotifyInfo extends com.qq.taf.jce.JceStruct
{
    public int nextpage = (int)0;

    public com.qq.taf.server.proxy.NotifyItem[] notifyItems;

    public int getNextpage()
    {
        return nextpage;
    }

    public void  setNextpage(int nextpage)
    {
        this.nextpage = nextpage;
    }

    public com.qq.taf.server.proxy.NotifyItem[] getNotifyItems()
    {
        return notifyItems;
    }

    public void  setNotifyItems(com.qq.taf.server.proxy.NotifyItem[] notifyItems)
    {
        this.notifyItems = notifyItems;
    }

    public NotifyInfo()
    {
    }

    public NotifyInfo(int nextpage, com.qq.taf.server.proxy.NotifyItem[] notifyItems)
    {
        this.nextpage = nextpage;
        this.notifyItems = notifyItems;
    }

    public boolean equals(Object o)
    {
        NotifyInfo t = (NotifyInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nextpage, t.nextpage) && 
            com.qq.taf.jce.JceUtil.equals(notifyItems, t.notifyItems) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nextpage, 1);
        _os.write(notifyItems, 2);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        nextpage = 0;
        nextpage = (int) _is.read(nextpage, 1, true);

        notifyItems = (com.qq.taf.server.proxy.NotifyItem[]) new com.qq.taf.server.proxy.NotifyItem[1];
        com.qq.taf.server.proxy.NotifyItem __var_1 = new com.qq.taf.server.proxy.NotifyItem();
        ((com.qq.taf.server.proxy.NotifyItem[])notifyItems)[0] = __var_1;
        notifyItems = (com.qq.taf.server.proxy.NotifyItem[]) _is.read(notifyItems, 2, true);

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(nextpage, "nextpage");
        _ds.display(notifyItems, "notifyItems");
    }

}
