// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `./PropertyF.jce'
// **********************************************************************

package com.qq.taf.server.proxy;

public final class PropertyFPrxHelper extends com.qq.taf.proxy.ServantProxy implements PropertyFPrx
{

    public PropertyFPrxHelper taf_hash(int hashCode)
    {
        super.taf_hash(hashCode);
        return this;
    }

    public java.util.Map __defaultContext()
    {
        java.util.HashMap _ctx = new java.util.HashMap();
        return _ctx;
    }

    protected String sServerEncoding = "GBK";
    public int setServerEncoding(String se){
        sServerEncoding = se;
        return 0;
    }

    public int reportPropMsg(java.util.Map<com.qq.taf.server.proxy.StatPropMsgHead, com.qq.taf.server.proxy.StatPropMsgBody> statmsg)
    {
        return reportPropMsg(statmsg, __defaultContext());
    }

    @SuppressWarnings("unchecked")
    public int reportPropMsg(java.util.Map<com.qq.taf.server.proxy.StatPropMsgHead, com.qq.taf.server.proxy.StatPropMsgBody> statmsg, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(statmsg, 1);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> status = new java.util.HashMap<String, String>();

        byte[] _returnSBuffer = taf_invoke("reportPropMsg", _sBuffer, __ctx, status);

        com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(_returnSBuffer);
        _is.setServerEncoding(sServerEncoding);
        int _ret = 0;
        _ret = (int) _is.read(_ret, 0, true);
        return _ret;
    }

    public void async_reportPropMsg(com.qq.taf.server.proxy.PropertyFPrxCallback callback, java.util.Map<com.qq.taf.server.proxy.StatPropMsgHead, com.qq.taf.server.proxy.StatPropMsgBody> statmsg)
    {
        async_reportPropMsg(callback, statmsg, __defaultContext());
    }

    public void async_reportPropMsg(com.qq.taf.server.proxy.PropertyFPrxCallback callback, java.util.Map<com.qq.taf.server.proxy.StatPropMsgHead, com.qq.taf.server.proxy.StatPropMsgBody> statmsg, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(statmsg, 1);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> status = new java.util.HashMap<String, String>();

        taf_invokeAsync(callback, "reportPropMsg", _sBuffer, __ctx, status);

    }

}
