// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `./PropertyF.jce'
// **********************************************************************

package com.qq.taf.server.proxy;

public final class StatPropMsgBodyHolder
{
    public StatPropMsgBodyHolder()
    {
    }
    public StatPropMsgBodyHolder(StatPropMsgBody value)
    {
        this.value = value;
    }

    public StatPropMsgBody value;
}
