
TOPDIR  := ../..
include ${TOPDIR}/make.rules

#-------------------------------------------------------------------------------

INCLUDE   +=
LIB       += ${TAFLIB}
#-------------------------------------------------------------------------------

TARGET  := TransServer
CONFIG  :=
STRIP_FLAG := Y

#release : $(TARGET)
#	@strip $(TARGET)
#	@sz $(TARGET)

#-------------------------------------------------------------------------------

include ${TOPDIR}/inc.mk
