// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class MSGID
{
    private static MSGID[] __values = new MSGID[22];
    private int __value;
    private String __T = new String();

    public static final int _MSGID_NULL = 0;
    public static final MSGID MSGID_NULL = new MSGID(_MSGID_NULL,"MSGID_NULL");
    public static final int _MSGID_HELLO = 1;
    public static final MSGID MSGID_HELLO = new MSGID(_MSGID_HELLO,"MSGID_HELLO");
    public static final int _MSGID_VERIFYCODE = 2;
    public static final MSGID MSGID_VERIFYCODE = new MSGID(_MSGID_VERIFYCODE,"MSGID_VERIFYCODE");
    public static final int _MSGID_LOGIN = 3;
    public static final MSGID MSGID_LOGIN = new MSGID(_MSGID_LOGIN,"MSGID_LOGIN");
    public static final int _MSGID_LOGOUT = 4;
    public static final MSGID MSGID_LOGOUT = new MSGID(_MSGID_LOGOUT,"MSGID_LOGOUT");
    public static final int _MSGID_LISTZONE = 5;
    public static final MSGID MSGID_LISTZONE = new MSGID(_MSGID_LISTZONE,"MSGID_LISTZONE");
    public static final int _MSGID_LISTROOM = 6;
    public static final MSGID MSGID_LISTROOM = new MSGID(_MSGID_LISTROOM,"MSGID_LISTROOM");
    public static final int _MSGID_LISTTABLE = 7;
    public static final MSGID MSGID_LISTTABLE = new MSGID(_MSGID_LISTTABLE,"MSGID_LISTTABLE");
    public static final int _MSGID_SITDOWN = 8;
    public static final MSGID MSGID_SITDOWN = new MSGID(_MSGID_SITDOWN,"MSGID_SITDOWN");
    public static final int _MSGID_STANDUP = 9;
    public static final MSGID MSGID_STANDUP = new MSGID(_MSGID_STANDUP,"MSGID_STANDUP");
    public static final int _MSGID_STARTGAME = 10;
    public static final MSGID MSGID_STARTGAME = new MSGID(_MSGID_STARTGAME,"MSGID_STARTGAME");
    public static final int _MSGID_PLAYDATA = 11;
    public static final MSGID MSGID_PLAYDATA = new MSGID(_MSGID_PLAYDATA,"MSGID_PLAYDATA");
    public static final int _MSGID_TALKONTABLE = 12;
    public static final MSGID MSGID_TALKONTABLE = new MSGID(_MSGID_TALKONTABLE,"MSGID_TALKONTABLE");
    public static final int _MSGID_KICKPLAYER = 13;
    public static final MSGID MSGID_KICKPLAYER = new MSGID(_MSGID_KICKPLAYER,"MSGID_KICKPLAYER");
    public static final int _MSGID_REPLAY = 14;
    public static final MSGID MSGID_REPLAY = new MSGID(_MSGID_REPLAY,"MSGID_REPLAY");
    public static final int _MSGID_QUERYTABLE = 15;
    public static final MSGID MSGID_QUERYTABLE = new MSGID(_MSGID_QUERYTABLE,"MSGID_QUERYTABLE");
    public static final int _MSGID_PUSH_GAMEEVENT = 16;
    public static final MSGID MSGID_PUSH_GAMEEVENT = new MSGID(_MSGID_PUSH_GAMEEVENT,"MSGID_PUSH_GAMEEVENT");
    public static final int _MSGID_PUSH_LOADRES = 17;
    public static final MSGID MSGID_PUSH_LOADRES = new MSGID(_MSGID_PUSH_LOADRES,"MSGID_PUSH_LOADRES");
    public static final int _MSGID_PUSH_ROOMEVENT = 18;
    public static final MSGID MSGID_PUSH_ROOMEVENT = new MSGID(_MSGID_PUSH_ROOMEVENT,"MSGID_PUSH_ROOMEVENT");
    public static final int _MSGID_PUSH_MESSAGE = 19;
    public static final MSGID MSGID_PUSH_MESSAGE = new MSGID(_MSGID_PUSH_MESSAGE,"MSGID_PUSH_MESSAGE");
    public static final int _MSGID_PUSH_SPEEDTEST = 20;
    public static final MSGID MSGID_PUSH_SPEEDTEST = new MSGID(_MSGID_PUSH_SPEEDTEST,"MSGID_PUSH_SPEEDTEST");
    public static final int _MSGID_PUSH_TABLEMSG = 21;
    public static final MSGID MSGID_PUSH_TABLEMSG = new MSGID(_MSGID_PUSH_TABLEMSG,"MSGID_PUSH_TABLEMSG");

    public static MSGID convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        return null;
    }

    public static MSGID convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private MSGID(int val, String s)
    {
        __T = s;
        __value = val;
        __values[val] = this;
    }

}
