// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgRequestStandUp extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgRequestStandUp";
    }

    public short nRoomID = (short)0;

    public short getNRoomID()
    {
        return nRoomID;
    }

    public void  setNRoomID(short nRoomID)
    {
        this.nRoomID = nRoomID;
    }

    public TMsgRequestStandUp()
    {
    }

    public TMsgRequestStandUp(short nRoomID)
    {
        this.nRoomID = nRoomID;
    }

    public boolean equals(Object o)
    {
        TMsgRequestStandUp t = (TMsgRequestStandUp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nRoomID, t.nRoomID) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nRoomID, 0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nRoomID = 0;
            nRoomID = (short) _is.read(nRoomID, 0, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
