// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgPushRoomEvent extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgPushRoomEvent";
    }

    public java.util.Vector vecRoomEvent = new java.util.Vector();

    public java.util.Vector getVecRoomEvent()
    {
        return vecRoomEvent;
    }

    public void  setVecRoomEvent(java.util.Vector vecRoomEvent)
    {
        this.vecRoomEvent = vecRoomEvent;
    }

    public TMsgPushRoomEvent()
    {
    }

    public TMsgPushRoomEvent(java.util.Vector vecRoomEvent)
    {
        this.vecRoomEvent = vecRoomEvent;
    }

    public boolean equals(Object o)
    {
        TMsgPushRoomEvent t = (TMsgPushRoomEvent) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vecRoomEvent, t.vecRoomEvent) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(vecRoomEvent, 0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            vecRoomEvent = new java.util.Vector();
            MiniGameProto.TRoomEvent __var_18 = new MiniGameProto.TRoomEvent();
            vecRoomEvent.addElement(__var_18);
            vecRoomEvent = (java.util.Vector) _is.read(vecRoomEvent, 0, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
