// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgHead extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgHead";
    }

    public short nMsgID = (short)0;

    public short nMsgType = (short)0;

    public short nMsgLen = (short)0;

    public short getNMsgID()
    {
        return nMsgID;
    }

    public void  setNMsgID(short nMsgID)
    {
        this.nMsgID = nMsgID;
    }

    public short getNMsgType()
    {
        return nMsgType;
    }

    public void  setNMsgType(short nMsgType)
    {
        this.nMsgType = nMsgType;
    }

    public short getNMsgLen()
    {
        return nMsgLen;
    }

    public void  setNMsgLen(short nMsgLen)
    {
        this.nMsgLen = nMsgLen;
    }

    public TMsgHead()
    {
    }

    public TMsgHead(short nMsgID, short nMsgType, short nMsgLen)
    {
        this.nMsgID = nMsgID;
        this.nMsgType = nMsgType;
        this.nMsgLen = nMsgLen;
    }

    public boolean equals(Object o)
    {
        TMsgHead t = (TMsgHead) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nMsgID, t.nMsgID) && 
            com.qq.taf.jce.JceUtil.equals(nMsgType, t.nMsgType) && 
            com.qq.taf.jce.JceUtil.equals(nMsgLen, t.nMsgLen) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nMsgID, 0);
            _os.write(nMsgType, 1);
            _os.write(nMsgLen, 2);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nMsgID = 0;
            nMsgID = (short) _is.read(nMsgID, 0, true);

            nMsgType = 0;
            nMsgType = (short) _is.read(nMsgType, 1, true);

            nMsgLen = 0;
            nMsgLen = (short) _is.read(nMsgLen, 2, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
