// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgRequestVerifyCode extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgRequestVerifyCode";
    }

    public short nOperation = (short)0;

    public byte [] vecSid = (byte[]) new byte[1];

    public byte [] vecVerifyCode = (byte[]) new byte[1];

    public short getNOperation()
    {
        return nOperation;
    }

    public void  setNOperation(short nOperation)
    {
        this.nOperation = nOperation;
    }

    public byte [] getVecSid()
    {
        return vecSid;
    }

    public void  setVecSid(byte [] vecSid)
    {
        this.vecSid = vecSid;
    }

    public byte [] getVecVerifyCode()
    {
        return vecVerifyCode;
    }

    public void  setVecVerifyCode(byte [] vecVerifyCode)
    {
        this.vecVerifyCode = vecVerifyCode;
    }

    public TMsgRequestVerifyCode()
    {
    }

    public TMsgRequestVerifyCode(short nOperation, byte [] vecSid, byte [] vecVerifyCode)
    {
        this.nOperation = nOperation;
        this.vecSid = vecSid;
        this.vecVerifyCode = vecVerifyCode;
    }

    public boolean equals(Object o)
    {
        TMsgRequestVerifyCode t = (TMsgRequestVerifyCode) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nOperation, t.nOperation) && 
            com.qq.taf.jce.JceUtil.equals(vecSid, t.vecSid) && 
            com.qq.taf.jce.JceUtil.equals(vecVerifyCode, t.vecVerifyCode) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nOperation, 0);
            _os.write(vecSid, 1);
            _os.write(vecVerifyCode, 2);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nOperation = 0;
            nOperation = (short) _is.read(nOperation, 0, true);

            vecSid = (byte[]) new byte[1];
            byte __var_8 = 0;
            ((byte[])vecSid)[0] = __var_8;
            vecSid = (byte []) _is.read(vecSid, 1, true);

            vecVerifyCode = (byte[]) new byte[1];
            byte __var_9 = 0;
            ((byte[])vecVerifyCode)[0] = __var_9;
            vecVerifyCode = (byte []) _is.read(vecVerifyCode, 2, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
