// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgRequestPlayData extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgRequestPlayData";
    }

    public byte [] strPlayData = (byte[]) new byte[1];

    public byte [] getStrPlayData()
    {
        return strPlayData;
    }

    public void  setStrPlayData(byte [] strPlayData)
    {
        this.strPlayData = strPlayData;
    }

    public TMsgRequestPlayData()
    {
    }

    public TMsgRequestPlayData(byte [] strPlayData)
    {
        this.strPlayData = strPlayData;
    }

    public boolean equals(Object o)
    {
        TMsgRequestPlayData t = (TMsgRequestPlayData) o;
        return (
            com.qq.taf.jce.JceUtil.equals(strPlayData, t.strPlayData) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(strPlayData, 0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            strPlayData = (byte[]) new byte[1];
            byte __var_16 = 0;
            ((byte[])strPlayData)[0] = __var_16;
            strPlayData = (byte []) _is.read(strPlayData, 0, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
