// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgPushMessage extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgPushMessage";
    }

    public short nAction = (short)0;

    public String strMsg = (String)"";

    public String strUrl = (String)"";

    public short getNAction()
    {
        return nAction;
    }

    public void  setNAction(short nAction)
    {
        this.nAction = nAction;
    }

    public String getStrMsg()
    {
        return strMsg;
    }

    public void  setStrMsg(String strMsg)
    {
        this.strMsg = strMsg;
    }

    public String getStrUrl()
    {
        return strUrl;
    }

    public void  setStrUrl(String strUrl)
    {
        this.strUrl = strUrl;
    }

    public TMsgPushMessage()
    {
    }

    public TMsgPushMessage(short nAction, String strMsg, String strUrl)
    {
        this.nAction = nAction;
        this.strMsg = strMsg;
        this.strUrl = strUrl;
    }

    public boolean equals(Object o)
    {
        TMsgPushMessage t = (TMsgPushMessage) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nAction, t.nAction) && 
            com.qq.taf.jce.JceUtil.equals(strMsg, t.strMsg) && 
            com.qq.taf.jce.JceUtil.equals(strUrl, t.strUrl) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nAction, 0);
            _os.write(strMsg, 1);
            _os.write(strUrl, 2);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nAction = 0;
            nAction = (short) _is.read(nAction, 0, true);

            strMsg = "";
            strMsg = (String) _is.read(strMsg, 1, true);

            strUrl = "";
            strUrl = (String) _is.read(strUrl, 2, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
