// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgPushTableMsg extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgPushTableMsg";
    }

    public int iUin = (int)0;

    public String strMsg = (String)"";

    public int getIUin()
    {
        return iUin;
    }

    public void  setIUin(int iUin)
    {
        this.iUin = iUin;
    }

    public String getStrMsg()
    {
        return strMsg;
    }

    public void  setStrMsg(String strMsg)
    {
        this.strMsg = strMsg;
    }

    public TMsgPushTableMsg()
    {
    }

    public TMsgPushTableMsg(int iUin, String strMsg)
    {
        this.iUin = iUin;
        this.strMsg = strMsg;
    }

    public boolean equals(Object o)
    {
        TMsgPushTableMsg t = (TMsgPushTableMsg) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iUin, t.iUin) && 
            com.qq.taf.jce.JceUtil.equals(strMsg, t.strMsg) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(iUin, 0);
            _os.write(strMsg, 1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            iUin = 0;
            iUin = (int) _is.read(iUin, 0, true);

            strMsg = "";
            strMsg = (String) _is.read(strMsg, 1, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
