// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgRequestListZone extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgRequestListZone";
    }

    public short nGameID = (short)0;

    public int iGameVersion = (int)0;

    public short nPage = (short)0;

    public short nZoneNumPerPage = (short)0;

    public short getNGameID()
    {
        return nGameID;
    }

    public void  setNGameID(short nGameID)
    {
        this.nGameID = nGameID;
    }

    public int getIGameVersion()
    {
        return iGameVersion;
    }

    public void  setIGameVersion(int iGameVersion)
    {
        this.iGameVersion = iGameVersion;
    }

    public short getNPage()
    {
        return nPage;
    }

    public void  setNPage(short nPage)
    {
        this.nPage = nPage;
    }

    public short getNZoneNumPerPage()
    {
        return nZoneNumPerPage;
    }

    public void  setNZoneNumPerPage(short nZoneNumPerPage)
    {
        this.nZoneNumPerPage = nZoneNumPerPage;
    }

    public TMsgRequestListZone()
    {
    }

    public TMsgRequestListZone(short nGameID, int iGameVersion, short nPage, short nZoneNumPerPage)
    {
        this.nGameID = nGameID;
        this.iGameVersion = iGameVersion;
        this.nPage = nPage;
        this.nZoneNumPerPage = nZoneNumPerPage;
    }

    public boolean equals(Object o)
    {
        TMsgRequestListZone t = (TMsgRequestListZone) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nGameID, t.nGameID) && 
            com.qq.taf.jce.JceUtil.equals(iGameVersion, t.iGameVersion) && 
            com.qq.taf.jce.JceUtil.equals(nPage, t.nPage) && 
            com.qq.taf.jce.JceUtil.equals(nZoneNumPerPage, t.nZoneNumPerPage) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nGameID, 0);
            _os.write(iGameVersion, 1);
            _os.write(nPage, 2);
            _os.write(nZoneNumPerPage, 3);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nGameID = 0;
            nGameID = (short) _is.read(nGameID, 0, true);

            iGameVersion = 0;
            iGameVersion = (int) _is.read(iGameVersion, 1, true);

            nPage = 0;
            nPage = (short) _is.read(nPage, 2, true);

            nZoneNumPerPage = 0;
            nZoneNumPerPage = (short) _is.read(nZoneNumPerPage, 3, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
