// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgResponseQueryTable extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgResponseQueryTable";
    }

    public short nResultID = (short)0;

    public short nRoomID = (short)0;

    public short nTableID = (short)0;

    public MiniGameProto.TTableInfo stTableInfo = new MiniGameProto.TTableInfo();

    public short getNResultID()
    {
        return nResultID;
    }

    public void  setNResultID(short nResultID)
    {
        this.nResultID = nResultID;
    }

    public short getNRoomID()
    {
        return nRoomID;
    }

    public void  setNRoomID(short nRoomID)
    {
        this.nRoomID = nRoomID;
    }

    public short getNTableID()
    {
        return nTableID;
    }

    public void  setNTableID(short nTableID)
    {
        this.nTableID = nTableID;
    }

    public MiniGameProto.TTableInfo getStTableInfo()
    {
        return stTableInfo;
    }

    public void  setStTableInfo(MiniGameProto.TTableInfo stTableInfo)
    {
        this.stTableInfo = stTableInfo;
    }

    public TMsgResponseQueryTable()
    {
    }

    public TMsgResponseQueryTable(short nResultID, short nRoomID, short nTableID, MiniGameProto.TTableInfo stTableInfo)
    {
        this.nResultID = nResultID;
        this.nRoomID = nRoomID;
        this.nTableID = nTableID;
        this.stTableInfo = stTableInfo;
    }

    public boolean equals(Object o)
    {
        TMsgResponseQueryTable t = (TMsgResponseQueryTable) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nResultID, t.nResultID) && 
            com.qq.taf.jce.JceUtil.equals(nRoomID, t.nRoomID) && 
            com.qq.taf.jce.JceUtil.equals(nTableID, t.nTableID) && 
            com.qq.taf.jce.JceUtil.equals(stTableInfo, t.stTableInfo) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(nResultID, 0);
            _os.write(nRoomID, 1);
            _os.write(nTableID, 2);
            _os.write(stTableInfo, 3);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            nResultID = 0;
            nResultID = (short) _is.read(nResultID, 0, true);

            nRoomID = 0;
            nRoomID = (short) _is.read(nRoomID, 1, true);

            nTableID = 0;
            nTableID = (short) _is.read(nTableID, 2, true);

            stTableInfo = new MiniGameProto.TTableInfo();
            stTableInfo = (MiniGameProto.TTableInfo) _is.read(stTableInfo, 3, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
