// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TMsgRequestLogout extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TMsgRequestLogout";
    }

    public int iTime = (int)0;

    public int getITime()
    {
        return iTime;
    }

    public void  setITime(int iTime)
    {
        this.iTime = iTime;
    }

    public TMsgRequestLogout()
    {
    }

    public TMsgRequestLogout(int iTime)
    {
        this.iTime = iTime;
    }

    public boolean equals(Object o)
    {
        TMsgRequestLogout t = (TMsgRequestLogout) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iTime, t.iTime) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(iTime, 0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            iTime = 0;
            iTime = (int) _is.read(iTime, 0, true);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
