// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MiniGameProto_new.jce'
// **********************************************************************

package MiniGameProto;

public final class TTestA extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MiniGameProto.TTestA";
    }

    public byte [] data = (byte[]) new byte[1];

    public byte [] getData()
    {
        return data;
    }

    public void  setData(byte [] data)
    {
        this.data = data;
    }

    public TTestA()
    {
    }

    public TTestA(byte [] data)
    {
        this.data = data;
    }

    public boolean equals(Object o)
    {
        TTestA t = (TTestA) o;
        return (
            com.qq.taf.jce.JceUtil.equals(data, t.data) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(data, 0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            data = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])data)[0] = __var_1;
            data = (byte []) _is.read(data, 0, false);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
