
TOPDIR	:= ../..

include ${TOPDIR}/make.rules

all:
	javac src/Hessian2hce.java

clean:
	@echo "do clean nothing"

cleanall:
	@echo "do cleanall nothing"

install:
	javac src/Hessian2hce.java
	cp -rf src/Hessian2hce.class ${INSTALL_PATH}/bin

uninstall:
	@echo "do uninstall nothing"

touch:
	@echo "do touch nothing"
