// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `NodeDescriptor.jce'
// **********************************************************************

package com.qq.taf;

public final class LoadInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "taf.LoadInfo";
    }

    public String fullClassName()
    {
        return "com.qq.taf.LoadInfo";
    }

    public float avg1 = 0;

    public float avg5 = 0;

    public float avg15 = 0;

    public float getAvg1()
    {
        return avg1;
    }

    public void  setAvg1(float avg1)
    {
        this.avg1 = avg1;
    }

    public float getAvg5()
    {
        return avg5;
    }

    public void  setAvg5(float avg5)
    {
        this.avg5 = avg5;
    }

    public float getAvg15()
    {
        return avg15;
    }

    public void  setAvg15(float avg15)
    {
        this.avg15 = avg15;
    }

    public LoadInfo()
    {
        setAvg1(avg1);
        setAvg5(avg5);
        setAvg15(avg15);
    }

    public LoadInfo(float avg1, float avg5, float avg15)
    {
        setAvg1(avg1);
        setAvg5(avg5);
        setAvg15(avg15);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        LoadInfo t = (LoadInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(avg1, t.avg1) && 
            com.qq.taf.jce.JceUtil.equals(avg5, t.avg5) && 
            com.qq.taf.jce.JceUtil.equals(avg15, t.avg15) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(avg1, 0);
        _os.write(avg5, 1);
        _os.write(avg15, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setAvg1((float) _is.read(avg1, 0, true));

        setAvg5((float) _is.read(avg5, 1, true));

        setAvg15((float) _is.read(avg15, 2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(avg1, "avg1");
        _ds.display(avg5, "avg5");
        _ds.display(avg15, "avg15");
    }

}

