// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `NodeDescriptor.jce'
// **********************************************************************

package com.qq.taf;

public final class NodeInfoHolder
{
    public NodeInfoHolder()
    {
    }
    public NodeInfoHolder(NodeInfo value)
    {
        this.value = value;
    }

    public NodeInfo value;
}
