// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `NodeDescriptor.jce'
// **********************************************************************

package com.qq.taf;

public final class PatchInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "taf.PatchInfo";
    }

    public String fullClassName()
    {
        return "com.qq.taf.PatchInfo";
    }

    public boolean bPatching = false;

    public int iPercent = 0;

    public int iModifyTime = 0;

    public String sVersion = "";

    public String sResult = "";

    public boolean bSucc = false;

    public boolean getBPatching()
    {
        return bPatching;
    }

    public void  setBPatching(boolean bPatching)
    {
        this.bPatching = bPatching;
    }

    public int getIPercent()
    {
        return iPercent;
    }

    public void  setIPercent(int iPercent)
    {
        this.iPercent = iPercent;
    }

    public int getIModifyTime()
    {
        return iModifyTime;
    }

    public void  setIModifyTime(int iModifyTime)
    {
        this.iModifyTime = iModifyTime;
    }

    public String getSVersion()
    {
        return sVersion;
    }

    public void  setSVersion(String sVersion)
    {
        this.sVersion = sVersion;
    }

    public String getSResult()
    {
        return sResult;
    }

    public void  setSResult(String sResult)
    {
        this.sResult = sResult;
    }

    public boolean getBSucc()
    {
        return bSucc;
    }

    public void  setBSucc(boolean bSucc)
    {
        this.bSucc = bSucc;
    }

    public PatchInfo()
    {
        setBPatching(bPatching);
        setIPercent(iPercent);
        setIModifyTime(iModifyTime);
        setSVersion(sVersion);
        setSResult(sResult);
        setBSucc(bSucc);
    }

    public PatchInfo(boolean bPatching, int iPercent, int iModifyTime, String sVersion, String sResult, boolean bSucc)
    {
        setBPatching(bPatching);
        setIPercent(iPercent);
        setIModifyTime(iModifyTime);
        setSVersion(sVersion);
        setSResult(sResult);
        setBSucc(bSucc);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PatchInfo t = (PatchInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(bPatching, t.bPatching) && 
            com.qq.taf.jce.JceUtil.equals(iPercent, t.iPercent) && 
            com.qq.taf.jce.JceUtil.equals(iModifyTime, t.iModifyTime) && 
            com.qq.taf.jce.JceUtil.equals(sVersion, t.sVersion) && 
            com.qq.taf.jce.JceUtil.equals(sResult, t.sResult) && 
            com.qq.taf.jce.JceUtil.equals(bSucc, t.bSucc) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(bPatching, 0);
        _os.write(iPercent, 1);
        _os.write(iModifyTime, 2);
        _os.write(sVersion, 3);
        _os.write(sResult, 4);
        _os.write(bSucc, 5);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setBPatching((boolean) _is.read(bPatching, 0, true));

        setIPercent((int) _is.read(iPercent, 1, true));

        setIModifyTime((int) _is.read(iModifyTime, 2, true));

        setSVersion( _is.readString(3, true));

        setSResult( _is.readString(4, true));

        setBSucc((boolean) _is.read(bSucc, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(bPatching, "bPatching");
        _ds.display(iPercent, "iPercent");
        _ds.display(iModifyTime, "iModifyTime");
        _ds.display(sVersion, "sVersion");
        _ds.display(sResult, "sResult");
        _ds.display(bSucc, "bSucc");
    }

}

