// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/MTT_3_25.jce'
// **********************************************************************

package MTT;

public final class UpdateRsp extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "MTT.UpdateRsp";
    }

    public int iStatus = (int)0;

    public String sURL = (String)"";

    public String sText = (String)"";

    public String sMark = (String)"";

    public int getIStatus()
    {
        return iStatus;
    }

    public void  setIStatus(int iStatus)
    {
        this.iStatus = iStatus;
    }

    public String getSURL()
    {
        return sURL;
    }

    public void  setSURL(String sURL)
    {
        this.sURL = sURL;
    }

    public String getSText()
    {
        return sText;
    }

    public void  setSText(String sText)
    {
        this.sText = sText;
    }

    public String getSMark()
    {
        return sMark;
    }

    public void  setSMark(String sMark)
    {
        this.sMark = sMark;
    }

    public UpdateRsp()
    {
    }

    public UpdateRsp(int iStatus, String sURL, String sText, String sMark)
    {
        this.iStatus = iStatus;
        this.sURL = sURL;
        this.sText = sText;
        this.sMark = sMark;
    }

    public boolean equals(Object o)
    {
        UpdateRsp t = (UpdateRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iStatus, t.iStatus) && 
            com.qq.taf.jce.JceUtil.equals(sURL, t.sURL) && 
            com.qq.taf.jce.JceUtil.equals(sText, t.sText) && 
            com.qq.taf.jce.JceUtil.equals(sMark, t.sMark) );
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        try
        {
            _os.write(iStatus, 0);
            _os.write(sURL, 1);
            _os.write(sText, 2);
            _os.write(sMark, 3);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        try
        {
            iStatus = 0;
            iStatus = (int) _is.read(iStatus, 0, true);

            sURL = "";
            sURL = (String) _is.read(sURL, 1, true);

            sText = "";
            sText = (String) _is.read(sText, 2, true);

            sMark = "";
            sMark = (String) _is.read(sMark, 3, false);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void display(java.lang.StringBuffer _os, int _level)
    {
    }

}
