
#-----------------------------------------------------------------------

APP       := MDW
TARGET    := LbsServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   +=  
LIB       +=  

#-----------------------------------------------------------------------

include /home/tafjce/QUAN/SecretServer/SecretServer.mk
include /home/tafjce/MDW/HeziUIServer/HeziUIServer.mk

include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
