
TOPDIR  := ../..
include ${TOPDIR}/make.rules

#-------------------------------------------------------------------------------
INCLUDE   += -I${TOPDIR}/include/servant/
LIB       += ${TAFLIB} 

#-------------------------------------------------------------------------------

TARGET  := TestStat

#-------------------------------------------------------------------------------

include ${TOPDIR}/jce/stat/Stat.mk
include ${TOPDIR}/inc.mk
