// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QUANUserId.h"

@interface QUANPostSecretReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(tUserId,setTUserId:)) QUANUserId* JV2_PROP_NM(o,0,tUserId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sBitUrl,setSBitUrl:)) NSString* JV2_PROP_NM(o,1,sBitUrl);
@property (nonatomic, assign, JV2_PROP_GS_V2(iColorId,setIColorId:)) JceInt32 JV2_PROP_NM(o,2,iColorId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sContent,setSContent:)) NSString* JV2_PROP_NM(o,3,sContent);
@property (nonatomic, retain, JV2_PROP_GS_V2(sLocal,setSLocal:)) NSString* JV2_PROP_NM(o,4,sLocal);
@property (nonatomic, retain, JV2_PROP_GS_V2(sCoord,setSCoord:)) NSString* JV2_PROP_NM(o,5,sCoord);

@end
