// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

#import "QUANPostFavorRsp.h"

@implementation QUANPostFavorRsp

@synthesize JV2_PROP_NM(o,0,iStatus);

+ (void)initialize
{
    if (self == [QUANPostFavorRsp class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"QUAN.PostFavorRsp";
}

@end
