// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

#import "QUANPostSecretReq.h"

@implementation QUANPostSecretReq

@synthesize JV2_PROP_NM(o,0,tUserId);
@synthesize JV2_PROP_NM(o,1,sBitUrl);
@synthesize JV2_PROP_NM(o,2,iColorId);
@synthesize JV2_PROP_NM(o,3,sContent);
@synthesize JV2_PROP_NM(o,4,sLocal);
@synthesize JV2_PROP_NM(o,5,sCoord);

+ (void)initialize
{
    if (self == [QUANPostSecretReq class]) {
        [QUANUserId initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sBitUrl) = DefaultJceString;
        JV2_PROP(sContent) = DefaultJceString;
        JV2_PROP(sLocal) = DefaultJceString;
        JV2_PROP(sCoord) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(tUserId) = nil;
    JV2_PROP(sBitUrl) = nil;
    JV2_PROP(sContent) = nil;
    JV2_PROP(sLocal) = nil;
    JV2_PROP(sCoord) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"QUAN.PostSecretReq";
}

@end
