// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface QUANPostSecretRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iStatus,setIStatus:)) JceInt32 JV2_PROP_NM(o,0,iStatus);

@end
