// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `SecretBase.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QUANContentInfo.h"

@interface QUANPostContentRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iStatus,setIStatus:)) JceInt32 JV2_PROP_NM(o,0,iStatus);
@property (nonatomic, retain, JV2_PROP_GS_V2(tContent,setTContent:)) QUANContentInfo* JV2_PROP_NM(o,1,tContent);

@end
