// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `Notify.jce'
// **********************************************************************

package com.qq.taf.server.jce2java;

public final class NOTIFYLEVEL
{
    private static NOTIFYLEVEL[] __values = new NOTIFYLEVEL[3];
    private int __value;
    final static private String[] __T =
    {
        "NOTIFYNORMAL",
        "NOTIFYWARN",
        "NOTIFYERROR"
    };

    public static final int _NOTIFYNORMAL = 0;
    public static final NOTIFYLEVEL NOTIFYNORMAL = new NOTIFYLEVEL(_NOTIFYNORMAL);
    public static final int _NOTIFYWARN = 1;
    public static final NOTIFYLEVEL NOTIFYWARN = new NOTIFYLEVEL(_NOTIFYWARN);
    public static final int _NOTIFYERROR = 2;
    public static final NOTIFYLEVEL NOTIFYERROR = new NOTIFYLEVEL(_NOTIFYERROR);

    public static NOTIFYLEVEL convert(int val)
    {
        assert val < 3;
        return __values[val];
    }

    public static NOTIFYLEVEL convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T[__value];
    }

    private NOTIFYLEVEL(int val)
    {
        __value = val;
        __values[val] = this;
    }

}
