// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.3.1 by WSRD Tencent.
// Generated from `./PropertyF.jce'
// **********************************************************************

package com.qq.taf.server.jce2java;

public final class StatPropMsgBody extends com.qq.taf.jce.JceStruct
{
    public com.qq.taf.server.jce2java.StatPropInfo[] vInfo;

    public com.qq.taf.server.jce2java.StatPropInfo[] getVInfo()
    {
        return vInfo;
    }

    public void  setVInfo(com.qq.taf.server.jce2java.StatPropInfo[] vInfo)
    {
        this.vInfo = vInfo;
    }

    public StatPropMsgBody()
    {
    }

    public StatPropMsgBody(com.qq.taf.server.jce2java.StatPropInfo[] vInfo)
    {
        this.vInfo = vInfo;
    }

    public boolean equals(Object o)
    {
        StatPropMsgBody t = (StatPropMsgBody) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vInfo, t.vInfo) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(vInfo, 0);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        vInfo = (com.qq.taf.server.jce2java.StatPropInfo[]) new com.qq.taf.server.jce2java.StatPropInfo[1];
        com.qq.taf.server.jce2java.StatPropInfo __var_3 = new com.qq.taf.server.jce2java.StatPropInfo();
        ((com.qq.taf.server.jce2java.StatPropInfo[])vInfo)[0] = __var_3;
        vInfo = (com.qq.taf.server.jce2java.StatPropInfo[]) _is.read(vInfo, 0, true);

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vInfo, "vInfo");
    }

}
