TOPDIR  := ../..
include ${TOPDIR}/make.rules

#-------------------------------------------------------------------------------
INCLUDE   += -I/usr/local/wbl/include -I/home/edwardsu/taf_trunk/include
LIB       += -L/usr/local/wbl/lib -lwbl -L/home/edwardsu/taf_trunk/lib

#INCLUDE   += -I/home/edwardsu/taf_trunk/makefile.taf
LIB       += ${TAFLIB}
#-------------------------------------------------------------------------------

TARGET  := TestAddConfig

#-------------------------------------------------------------------------------

include ${TOPDIR}/inc.mk