
#-----------------------------------------------------------------------

APP       := QUAN
TARGET    := UserInfoServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE += -I/home/zhengqiao
LIB 	+= ./libredisclient.a

#-----------------------------------------------------------------------

include /home/tafjce/QUAN/SecretServer/SecretServer.mk
include /usr/local/taf/makefile.taf
LIB       += -lmysqlclient -lz
#-----------------------------------------------------------------------
