
#-----------------------------------------------------------------------

APP       := Test
TARGET    := asyncClient
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

#INCLUDE   += -I/usr/local/mqq/wbl/include 
#LIB       += -L/usr/local/mqq/wbl/lib -lwbl

INCLUDE   += -I/usr/local/wbl-0.7/include
LIB       += -L/usr/local/wbl-0.7/lib -lwbl

#-----------------------------------------------------------------------

include /home/tafjce/Test/BServer/BServer.mk
include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
