// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.6 by WSRD Tencent.
// Generated from `Basic.jce'
// **********************************************************************

package com.qq.java.test.basic;

public final class SendHolder
{
    public SendHolder()
    {
    }
    public SendHolder(Send value)
    {
        this.value = value;
    }

    public Send value;
}
