
#-----------------------------------------------------------------------

APP       := Test
TARGET    := abClient
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   += -I/usr/local/mqq/wbl/include 
LIB       += -L/usr/local/mqq/wbl/lib -lwbl

#-----------------------------------------------------------------------

include /home/tafjce/Test/AServer/AServer.mk
include /home/tafjce/Test/BServer/BServer.mk
include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
