TOPDIR  := ../..

#-------------------------------------------------------------------------------

INCLUDE   += -I${TOPDIR}/include/servant
LIB       += ${TAFLIB}

#-------------------------------------------------------------------------------

APP       := MDeskTop
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N

TARGET  := tafxmlproxy

#-------------------------------------------------------------------------------
TAF_PATH        := /home/kevintian/dev_taf
include ${TAF_PATH}/makefile.taf
