APP       	:= Test
TARGET		:= KevinTestServer
MFLAGS    	:= 32
CONFIG    	:= 
STRIP_FLAG	:= N


LIB       += 

#TAF_PATH	:= /home/kevintian/dev_taf/Taf_Beta06_Build004_B003
#include ${TAF_PATH}/makefile.taf
#include /usr/local/taf-version/taf-1.6.0/makefile.taf
#include /usr/local/taf/makefile.taf
TAF_PATH:=/home/kevintian/dev_taf/TAF_Trunk
include ${TAF_PATH}/makefile.taf
