// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttBrokerDisplayInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenWidth,setWScreenWidth:)) JceInt16 JV2_PROP_NM(o,0,wScreenWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenHeight,setWScreenHeight:)) JceInt16 JV2_PROP_NM(o,1,wScreenHeight);
@property (nonatomic, assign, JV2_PROP_GS_V2(cFontSize,setCFontSize:)) JceInt8 JV2_PROP_NM(o,2,cFontSize);
@property (nonatomic, assign, JV2_PROP_GS_V2(cRowSpacing,setCRowSpacing:)) JceInt8 JV2_PROP_NM(o,3,cRowSpacing);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,4,vCharSetKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(cSupportedImage,setCSupportedImage:)) JceInt8 JV2_PROP_NM(o,5,cSupportedImage);

@end
