// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttBrokerTransferResponse.h"

@implementation MttBrokerTransferResponse

@synthesize JV2_PROP_NM(r,0,sSession);
@synthesize JV2_PROP_NM(r,1,wTabId);
@synthesize JV2_PROP_NM(r,2,sPageEncodeName);
@synthesize JV2_PROP_NM(r,3,cDirectWap);
@synthesize JV2_PROP_NM(r,4,sDirectWapUrl);
@synthesize JV2_PROP_NM(r,5,iContentTimeStamp);
@synthesize JV2_PROP_NM(r,6,sFragKey);
@synthesize JV2_PROP_NM(r,7,iRspContentLen);
@synthesize JV2_PROP_NM(o,8,sUserSession);
@synthesize JV2_PROP_NM(o,9,stPushResp);
@synthesize JV2_PROP_NM(o,10,stSecurityResp);
@synthesize JV2_PROP_NM(o,11,cShare);

+ (void)initialize
{
    if (self == [MttBrokerTransferResponse class]) {
        [MttBrokerPushResponse initialize];
        [MttBrokerSecurityResponse initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSession) = DefaultJceString;
        JV2_PROP(sPageEncodeName) = DefaultJceString;
        JV2_PROP(sDirectWapUrl) = DefaultJceString;
        JV2_PROP(sFragKey) = DefaultJceString;
        JV2_PROP(sUserSession) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sSession) = nil;
    JV2_PROP(sPageEncodeName) = nil;
    JV2_PROP(sDirectWapUrl) = nil;
    JV2_PROP(sFragKey) = nil;
    JV2_PROP(sUserSession) = nil;
    JV2_PROP(stPushResp) = nil;
    JV2_PROP(stSecurityResp) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.BrokerTransferResponse";
}

@end
