// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttBrokerSecurityResponse : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iSecurityLevel,setISecurityLevel:)) JceInt32 JV2_PROP_NM(o,0,iSecurityLevel);
@property (nonatomic, retain, JV2_PROP_GS_V2(strSecurityType,setStrSecurityType:)) NSString* JV2_PROP_NM(o,1,strSecurityType);
@property (nonatomic, retain, JV2_PROP_GS_V2(vDetailDescription,setVDetailDescription:)) NSData* JV2_PROP_NM(o,2,vDetailDescription);

@end
