// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttBrokerUserInfo.h"
#import "MttPushAppReqList.h"

@interface MttBrokerPushRequest : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUserInfo,setStUserInfo:)) MttBrokerUserInfo* JV2_PROP_NM(o,0,stUserInfo);
@property (nonatomic, retain, JV2_PROP_GS_V2(strCookie,setStrCookie:)) NSString* JV2_PROP_NM(o,1,strCookie);
@property (nonatomic, assign, JV2_PROP_GS_V2(iPushTime,setIPushTime:)) JceInt32 JV2_PROP_NM(r,2,iPushTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPushAppReqData,setVPushAppReqData:)) NSArray* JV2_PROP_EX(r,3,vPushAppReqData,VOMTTPushAppReqList);

@end
