// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttBrokerPicParam.h"

@implementation MttBrokerPicParam

@synthesize JV2_PROP_EX(r,0,vsUrl,VONSString);
@synthesize JV2_PROP_NM(r,1,sCookie);

+ (void)initialize
{
    if (self == [MttBrokerPicParam class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vsUrl) = DefaultJceArray;
        JV2_PROP(sCookie) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vsUrl) = nil;
    JV2_PROP(sCookie) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.BrokerPicParam";
}

@end
