// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttPushRespnoseContent.h"

@interface MttBrokerPushResponse : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iPushTime,setIPushTime:)) JceInt32 JV2_PROP_NM(r,0,iPushTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPushRespContentList,setVPushRespContentList:)) NSArray* JV2_PROP_EX(r,1,vPushRespContentList,VOMTTPushRespnoseContent);

@end
