// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttBrowserVersion_OLDWAP1,
    MttBrowserVersion_OLDWAP2,
    MttBrowserVersion_NEWWAP1,
    MttBrowserVersion_NEWWAP2,
    MttBrowserVersion_HTML5
};
#define MttBrowserVersion NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttBrowserVersionHelper: JceEnumHelper

+ (NSString *)etos:(MttBrowserVersion)e;
+ (MttBrowserVersion)stoe:(NSString *)s;

@end

#endif
