// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttCheckPluginReq.h"

@implementation MttCheckPluginReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_EX(r,1,vItems,VOMTTPluginVersion);

+ (void)initialize
{
    if (self == [MttCheckPluginReq class]) {
        [MttPluginVersion initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(vItems) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(vItems) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.CheckPluginReq";
}

@end
