// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttDirectPolicy_DIRECT_DOMAIN,
    MttDirectPolicy_DIRECT_NONE
};
#define MttDirectPolicy NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttDirectPolicyHelper: JceEnumHelper

+ (NSString *)etos:(MttDirectPolicy)e;
+ (MttDirectPolicy)stoe:(NSString *)s;

@end

#endif
