// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttExtDomain.h"

@interface MttDomainRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vDomain,setVDomain:)) NSArray* JV2_PROP_EX(r,0,vDomain,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(iDomainTime,setIDomainTime:)) JceInt32 JV2_PROP_NM(r,1,iDomainTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vStatUrl,setVStatUrl:)) NSArray* JV2_PROP_EX(o,2,vStatUrl,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vReportUrl,setVReportUrl:)) NSArray* JV2_PROP_EX(o,3,vReportUrl,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vLbsDomain,setVLbsDomain:)) NSArray* JV2_PROP_EX(o,4,vLbsDomain,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vExtDomain,setVExtDomain:)) NSArray* JV2_PROP_EX(o,5,vExtDomain,VOMTTExtDomain);

@end
