// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttDomainRsp.h"

@implementation MttDomainRsp

@synthesize JV2_PROP_EX(r,0,vDomain,VONSString);
@synthesize JV2_PROP_NM(r,1,iDomainTime);
@synthesize JV2_PROP_EX(o,2,vStatUrl,VONSString);
@synthesize JV2_PROP_EX(o,3,vReportUrl,VONSString);
@synthesize JV2_PROP_EX(o,4,vLbsDomain,VONSString);
@synthesize JV2_PROP_EX(o,5,vExtDomain,VOMTTExtDomain);

+ (void)initialize
{
    if (self == [MttDomainRsp class]) {
        [MttExtDomain initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vDomain) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vDomain) = nil;
    JV2_PROP(vStatUrl) = nil;
    JV2_PROP(vReportUrl) = nil;
    JV2_PROP(vLbsDomain) = nil;
    JV2_PROP(vExtDomain) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.DomainRsp";
}

@end
