// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttDirectPolicy.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttDirectPolicyHelper

+ (NSString *)etos:(MttDirectPolicy)e
{
    switch(e){
        case MttDirectPolicy_DIRECT_DOMAIN: return @"MttDirectPolicy_DIRECT_DOMAIN";
        case MttDirectPolicy_DIRECT_NONE: return @"MttDirectPolicy_DIRECT_NONE";
        default: return @"";
    }
}

+ (MttDirectPolicy)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttDirectPolicy_DIRECT_DOMAIN")) return MttDirectPolicy_DIRECT_DOMAIN;
    if(isJceEnumStringEqual(s, @"MttDirectPolicy_DIRECT_NONE")) return MttDirectPolicy_DIRECT_NONE;
    return NSIntegerMin;
}

@end

#endif
