// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttEDomainType.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEDomainTypeHelper

+ (NSString *)etos:(MttEDomainType)e
{
    switch(e){
        case MttEDomainType_InnerDomain: return @"MttEDomainType_InnerDomain";
        case MttEDomainType_StatUrl: return @"MttEDomainType_StatUrl";
        case MttEDomainType_ReportUrl: return @"MttEDomainType_ReportUrl";
        case MttEDomainType_LbsUrl: return @"MttEDomainType_LbsUrl";
        case MttEDomainType_ReadModel: return @"MttEDomainType_ReadModel";
        case MttEDomainType_NovelModel: return @"MttEDomainType_NovelModel";
        case MttEDomainType_NetDisk: return @"MttEDomainType_NetDisk";
        case MttEDomainType_MsgBox: return @"MttEDomainType_MsgBox";
        case MttEDomainType_BookMarks: return @"MttEDomainType_BookMarks";
        case MttEDomainType_UserCenter: return @"MttEDomainType_UserCenter";
        case MttEDomainType_MicroBlogTextShare: return @"MttEDomainType_MicroBlogTextShare";
        case MttEDomainType_MicroBlogPicShare: return @"MttEDomainType_MicroBlogPicShare";
        case MttEDomainType_ReqBroker: return @"MttEDomainType_ReqBroker";
        case MttEDomainType_WebkitModel: return @"MttEDomainType_WebkitModel";
        case MttEDomainType_ACPortal: return @"MttEDomainType_ACPortal";
        case MttEDomainType_DownLoadAddr: return @"MttEDomainType_DownLoadAddr";
        case MttEDomainType_InfoCenter: return @"MttEDomainType_InfoCenter";
        case MttEDomainType_NovelCenter: return @"MttEDomainType_NovelCenter";
        case MttEDomainType_SMSAddr: return @"MttEDomainType_SMSAddr";
        case MttEDomainType_SafeWhiteList: return @"MttEDomainType_SafeWhiteList";
        case MttEDomainType_SafeReport: return @"MttEDomainType_SafeReport";
        case MttEDomainType_DirectWap: return @"MttEDomainType_DirectWap";
        case MttEDomainType_SaveToNetDisk: return @"MttEDomainType_SaveToNetDisk";
        case MttEDomainType_KjavaMiniHelp: return @"MttEDomainType_KjavaMiniHelp";
        case MttEDomainType_AliPayWhiteList: return @"MttEDomainType_AliPayWhiteList";
        case MttEDomainType_MttModel4ADR: return @"MttEDomainType_MttModel4ADR";
        case MttEDomainType_MttRegexModel4ADR: return @"MttEDomainType_MttRegexModel4ADR";
        case MttEDomainType_WebkitRegexModel4ADR: return @"MttEDomainType_WebkitRegexModel4ADR";
        case MttEDomainType_WebkitModel4ADR: return @"MttEDomainType_WebkitModel4ADR";
        case MttEDomainType_SimpleWindow: return @"MttEDomainType_SimpleWindow";
        case MttEDomainType_SafeWhiteList4IPAD: return @"MttEDomainType_SafeWhiteList4IPAD";
        case MttEDomainType_AdsPush: return @"MttEDomainType_AdsPush";
        case MttEDomainType_MTTModel4Iphone: return @"MttEDomainType_MTTModel4Iphone";
        case MttEDomainType_MTTRegexModel4Iphone: return @"MttEDomainType_MTTRegexModel4Iphone";
        case MttEDomainType_WebkitModel4Iphone: return @"MttEDomainType_WebkitModel4Iphone";
        case MttEDomainType_WebkitRegexModel4Iphone: return @"MttEDomainType_WebkitRegexModel4Iphone";
        case MttEDomainType_ChangeCityUrl: return @"MttEDomainType_ChangeCityUrl";
        case MttEDomainType_NetNoteUrl: return @"MttEDomainType_NetNoteUrl";
        case MttEDomainType_Upload2NetDiskUrl: return @"MttEDomainType_Upload2NetDiskUrl";
        case MttEDomainType_DownloadNetDiskUrl: return @"MttEDomainType_DownloadNetDiskUrl";
        case MttEDomainType_HotWordUrl1: return @"MttEDomainType_HotWordUrl1";
        case MttEDomainType_HotWordUrl2: return @"MttEDomainType_HotWordUrl2";
        case MttEDomainType_NeedQProxy: return @"MttEDomainType_NeedQProxy";
        case MttEDomainType_PerformanceStatUrl: return @"MttEDomainType_PerformanceStatUrl";
        case MttEDomainType_WebkitModelExt25: return @"MttEDomainType_WebkitModelExt25";
        default: return @"";
    }
}

+ (MttEDomainType)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttEDomainType_InnerDomain")) return MttEDomainType_InnerDomain;
    if(isJceEnumStringEqual(s, @"MttEDomainType_StatUrl")) return MttEDomainType_StatUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_ReportUrl")) return MttEDomainType_ReportUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_LbsUrl")) return MttEDomainType_LbsUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_ReadModel")) return MttEDomainType_ReadModel;
    if(isJceEnumStringEqual(s, @"MttEDomainType_NovelModel")) return MttEDomainType_NovelModel;
    if(isJceEnumStringEqual(s, @"MttEDomainType_NetDisk")) return MttEDomainType_NetDisk;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MsgBox")) return MttEDomainType_MsgBox;
    if(isJceEnumStringEqual(s, @"MttEDomainType_BookMarks")) return MttEDomainType_BookMarks;
    if(isJceEnumStringEqual(s, @"MttEDomainType_UserCenter")) return MttEDomainType_UserCenter;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MicroBlogTextShare")) return MttEDomainType_MicroBlogTextShare;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MicroBlogPicShare")) return MttEDomainType_MicroBlogPicShare;
    if(isJceEnumStringEqual(s, @"MttEDomainType_ReqBroker")) return MttEDomainType_ReqBroker;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitModel")) return MttEDomainType_WebkitModel;
    if(isJceEnumStringEqual(s, @"MttEDomainType_ACPortal")) return MttEDomainType_ACPortal;
    if(isJceEnumStringEqual(s, @"MttEDomainType_DownLoadAddr")) return MttEDomainType_DownLoadAddr;
    if(isJceEnumStringEqual(s, @"MttEDomainType_InfoCenter")) return MttEDomainType_InfoCenter;
    if(isJceEnumStringEqual(s, @"MttEDomainType_NovelCenter")) return MttEDomainType_NovelCenter;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SMSAddr")) return MttEDomainType_SMSAddr;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SafeWhiteList")) return MttEDomainType_SafeWhiteList;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SafeReport")) return MttEDomainType_SafeReport;
    if(isJceEnumStringEqual(s, @"MttEDomainType_DirectWap")) return MttEDomainType_DirectWap;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SaveToNetDisk")) return MttEDomainType_SaveToNetDisk;
    if(isJceEnumStringEqual(s, @"MttEDomainType_KjavaMiniHelp")) return MttEDomainType_KjavaMiniHelp;
    if(isJceEnumStringEqual(s, @"MttEDomainType_AliPayWhiteList")) return MttEDomainType_AliPayWhiteList;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MttModel4ADR")) return MttEDomainType_MttModel4ADR;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MttRegexModel4ADR")) return MttEDomainType_MttRegexModel4ADR;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitRegexModel4ADR")) return MttEDomainType_WebkitRegexModel4ADR;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitModel4ADR")) return MttEDomainType_WebkitModel4ADR;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SimpleWindow")) return MttEDomainType_SimpleWindow;
    if(isJceEnumStringEqual(s, @"MttEDomainType_SafeWhiteList4IPAD")) return MttEDomainType_SafeWhiteList4IPAD;
    if(isJceEnumStringEqual(s, @"MttEDomainType_AdsPush")) return MttEDomainType_AdsPush;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MTTModel4Iphone")) return MttEDomainType_MTTModel4Iphone;
    if(isJceEnumStringEqual(s, @"MttEDomainType_MTTRegexModel4Iphone")) return MttEDomainType_MTTRegexModel4Iphone;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitModel4Iphone")) return MttEDomainType_WebkitModel4Iphone;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitRegexModel4Iphone")) return MttEDomainType_WebkitRegexModel4Iphone;
    if(isJceEnumStringEqual(s, @"MttEDomainType_ChangeCityUrl")) return MttEDomainType_ChangeCityUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_NetNoteUrl")) return MttEDomainType_NetNoteUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_Upload2NetDiskUrl")) return MttEDomainType_Upload2NetDiskUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_DownloadNetDiskUrl")) return MttEDomainType_DownloadNetDiskUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_HotWordUrl1")) return MttEDomainType_HotWordUrl1;
    if(isJceEnumStringEqual(s, @"MttEDomainType_HotWordUrl2")) return MttEDomainType_HotWordUrl2;
    if(isJceEnumStringEqual(s, @"MttEDomainType_NeedQProxy")) return MttEDomainType_NeedQProxy;
    if(isJceEnumStringEqual(s, @"MttEDomainType_PerformanceStatUrl")) return MttEDomainType_PerformanceStatUrl;
    if(isJceEnumStringEqual(s, @"MttEDomainType_WebkitModelExt25")) return MttEDomainType_WebkitModelExt25;
    return NSIntegerMin;
}

@end

#endif
