// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttErrorCode.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttErrorCodeHelper

+ (NSString *)etos:(MttErrorCode)e
{
    switch(e){
        case MttErrorCode_ERROR_PROTOCOL: return @"MttErrorCode_ERROR_PROTOCOL";
        case MttErrorCode_ERROR_REFUSE_REQUEST: return @"MttErrorCode_ERROR_REFUSE_REQUEST";
        case MttErrorCode_ERROR_UNSUPPORTED_VERSION: return @"MttErrorCode_ERROR_UNSUPPORTED_VERSION";
        default: return @"";
    }
}

+ (MttErrorCode)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"MttErrorCode_ERROR_PROTOCOL")) return MttErrorCode_ERROR_PROTOCOL;
    if(isJceEnumStringEqual(s, @"MttErrorCode_ERROR_REFUSE_REQUEST")) return MttErrorCode_ERROR_REFUSE_REQUEST;
    if(isJceEnumStringEqual(s, @"MttErrorCode_ERROR_UNSUPPORTED_VERSION")) return MttErrorCode_ERROR_UNSUPPORTED_VERSION;
    return NSIntegerMin;
}

@end

#endif
