// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttFKINFO : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iStyle,setIStyle:)) JceInt32 JV2_PROP_NM(r,0,iStyle);
@property (nonatomic, assign, JV2_PROP_GS_V2(eFastKey,setEFastKey:)) JceInt32 JV2_PROP_NM(r,1,eFastKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(sKey,setSKey:)) NSString* JV2_PROP_NM(r,2,sKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUse,setIUse:)) JceInt32 JV2_PROP_NM(r,3,iUse);

@end
