// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttItemReq.h"

@implementation MttItemReq

@synthesize JV2_PROP_NM(r,0,itemId);
@synthesize JV2_PROP_NM(r,1,lastUpdateTime);

+ (void)initialize
{
    if (self == [MttItemReq class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.ItemReq";
}

@end
