// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttImgRsp.h"

@implementation MttImgRsp

@synthesize JV2_PROP_NM(o,0,sName);
@synthesize JV2_PROP_NM(o,1,sData);
@synthesize JV2_PROP_NM(o,2,iImgTime);
@synthesize JV2_PROP_NM(o,3,iLinkType);

+ (void)initialize
{
    if (self == [MttImgRsp class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sName) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sName) = nil;
    JV2_PROP(sData) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.ImgRsp";
}

@end
