// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttImgRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sName,setSName:)) NSString* JV2_PROP_NM(o,0,sName);
@property (nonatomic, retain, JV2_PROP_GS_V2(sData,setSData:)) NSData* JV2_PROP_NM(o,1,sData);
@property (nonatomic, assign, JV2_PROP_GS_V2(iImgTime,setIImgTime:)) JceInt32 JV2_PROP_NM(o,2,iImgTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iLinkType,setILinkType:)) JceInt32 JV2_PROP_NM(o,3,iLinkType);

@end
