// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttKeywordRsp.h"

@implementation MttKeywordRsp

@synthesize JV2_PROP_EX(r,0,vWordInfo,VONSString);
@synthesize JV2_PROP_NM(r,1,iKeywordTime);

+ (void)initialize
{
    if (self == [MttKeywordRsp class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vWordInfo) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vWordInfo) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.KeywordRsp";
}

@end
