// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttSTSingleMD5.h"
#import "MttUpdateRsp.h"
#import "MttVerifyRspExt.h"

@interface MttLoginRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sGUID,setSGUID:)) NSData* JV2_PROP_NM(r,0,sGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(vAuth,setVAuth:)) NSData* JV2_PROP_NM(r,1,vAuth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iTime,setITime:)) JceInt32 JV2_PROP_NM(r,2,iTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vProxyList,setVProxyList:)) NSArray* JV2_PROP_EX(r,3,vProxyList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vRelayList,setVRelayList:)) NSArray* JV2_PROP_EX(r,4,vRelayList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(stUpdateRsp,setStUpdateRsp:)) MttUpdateRsp* JV2_PROP_NM(r,5,stUpdateRsp);
@property (nonatomic, retain, JV2_PROP_GS_V2(stVerifyRspExt,setStVerifyRspExt:)) MttVerifyRspExt* JV2_PROP_NM(o,6,stVerifyRspExt);
@property (nonatomic, assign, JV2_PROP_GS_V2(iStatValue,setIStatValue:)) JceInt32 JV2_PROP_NM(o,7,iStatValue);
@property (nonatomic, retain, JV2_PROP_GS_V2(vRelayHttpsList,setVRelayHttpsList:)) NSData* JV2_PROP_NM(o,8,vRelayHttpsList);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,10,vCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vMidCharSetKey,setVMidCharSetKey:)) NSData* JV2_PROP_NM(o,11,vMidCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vBigCharSetKey,setVBigCharSetKey:)) NSData* JV2_PROP_NM(o,12,vBigCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetMD5Group,setVCharSetMD5Group:)) NSArray* JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHttpProxySession,setIHttpProxySession:)) JceInt32 JV2_PROP_NM(o,14,iHttpProxySession);
@property (nonatomic, retain, JV2_PROP_GS_V2(vQProxyList,setVQProxyList:)) NSArray* JV2_PROP_EX(o,15,vQProxyList,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(cProtocolFlag,setCProtocolFlag:)) JceInt8 JV2_PROP_NM(o,16,cProtocolFlag);

@end
