// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttLoginReq.h"

@implementation MttLoginReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,sOrigGUID);
@synthesize JV2_PROP_NM(r,2,vCrypt);
@synthesize JV2_PROP_NM(r,3,iWidth);
@synthesize JV2_PROP_NM(r,4,iHeight);
@synthesize JV2_PROP_NM(o,5,sChannel);
@synthesize JV2_PROP_NM(r,6,eRelayProtoVer);
@synthesize JV2_PROP_NM(o,7,sMark);
@synthesize JV2_PROP_NM(o,8,iVerifyId);
@synthesize JV2_PROP_NM(o,9,vCharSet);
@synthesize JV2_PROP_NM(o,10,vMidCharSet);
@synthesize JV2_PROP_NM(o,11,vBigCharSet);
@synthesize JV2_PROP_NM(o,12,vCharSetMD5);
@synthesize JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@synthesize JV2_PROP_NM(o,14,bHttpProxy);
@synthesize JV2_PROP_NM(o,15,bCrashTag);

+ (void)initialize
{
    if (self == [MttLoginReq class]) {
        [MttSTSingleMD5 initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(sOrigGUID) = DefaultJceData;
        JV2_PROP(vCrypt) = DefaultJceData;
        JV2_PROP(sChannel) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(sOrigGUID) = nil;
    JV2_PROP(vCrypt) = nil;
    JV2_PROP(sChannel) = nil;
    JV2_PROP(sMark) = nil;
    JV2_PROP(vCharSet) = nil;
    JV2_PROP(vMidCharSet) = nil;
    JV2_PROP(vBigCharSet) = nil;
    JV2_PROP(vCharSetMD5) = nil;
    JV2_PROP(vCharSetMD5Group) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.LoginReq";
}

@end
