// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttMethod_GET,
    MttMethod_POST,
    MttMethod_CONNECT,
    MttMethod_CONNECTDATA
};
#define MttMethod NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttMethodHelper: JceEnumHelper

+ (NSString *)etos:(MttMethod)e;
+ (MttMethod)stoe:(NSString *)s;

@end

#endif
