// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPluginVersion.h"

@implementation MttPluginVersion

@synthesize JV2_PROP_NM(r,0,sType);
@synthesize JV2_PROP_NM(o,1,sVersion);
@synthesize JV2_PROP_EX(o,2,mSpecCond,M09ONSStringONSString);

+ (void)initialize
{
    if (self == [MttPluginVersion class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sType) = DefaultJceString;
        JV2_PROP(sVersion) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sType) = nil;
    JV2_PROP(sVersion) = nil;
    JV2_PROP(mSpecCond) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PluginVersion";
}

@end
