// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttPluginRspNew.h"

@interface MttPluginBootResp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(pluginRsp,setPluginRsp:)) MttPluginRspNew* JV2_PROP_NM(o,0,pluginRsp);

@end
