// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttItemRsp.h"

@interface MttPageRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(pageId,setPageId:)) JceInt32 JV2_PROP_NM(r,0,pageId);
@property (nonatomic, assign, JV2_PROP_GS_V2(updateAll,setUpdateAll:)) JceInt8 JV2_PROP_NM(r,1,updateAll);
@property (nonatomic, assign, JV2_PROP_GS_V2(lastUpdateTime,setLastUpdateTime:)) JceInt32 JV2_PROP_NM(r,2,lastUpdateTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(top,setTop:)) NSString* JV2_PROP_NM(r,3,top);
@property (nonatomic, retain, JV2_PROP_GS_V2(foot,setFoot:)) NSString* JV2_PROP_NM(r,4,foot);
@property (nonatomic, retain, JV2_PROP_GS_V2(items,setItems:)) NSArray* JV2_PROP_EX(r,5,items,VOMTTItemRsp);

@end
