// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttPluginBootResp.h"

@implementation MttPluginBootResp

@synthesize JV2_PROP_NM(o,0,pluginRsp);

+ (void)initialize
{
    if (self == [MttPluginBootResp class]) {
        [MttPluginRspNew initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(pluginRsp) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.PluginBootResp";
}

@end
