// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "MttContentEncoding.h"

@interface MttReply : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(wVersion,setWVersion:)) JceInt32 JV2_PROP_NM(r,0,wVersion);
@property (nonatomic, retain, JV2_PROP_GS_V2(sSessionID,setSSessionID:)) NSString* JV2_PROP_NM(r,1,sSessionID);
@property (nonatomic, assign, JV2_PROP_GS_V2(iRequestID,setIRequestID:)) JceInt32 JV2_PROP_NM(r,2,iRequestID);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSequenceID,setISequenceID:)) JceInt32 JV2_PROP_NM(r,3,iSequenceID);
@property (nonatomic, assign, JV2_PROP_GS_V2(cFinishFlag,setCFinishFlag:)) JceInt8 JV2_PROP_NM(r,4,cFinishFlag);
@property (nonatomic, assign, JV2_PROP_GS_V2(eContentEncoding,setEContentEncoding:)) MttContentEncoding JV2_PROP_NM(r,5,eContentEncoding);

@end
