// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttRelayPageRsp.h"

@implementation MttRelayPageRsp

@synthesize JV2_PROP_NM(r,0,iPageSize);
@synthesize JV2_PROP_NM(r,1,eDirectPolicy);
@synthesize JV2_PROP_NM(r,2,sPageOrigEncode);
@synthesize JV2_PROP_NM(o,3,sDirectDomain);

+ (void)initialize
{
    if (self == [MttRelayPageRsp class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sPageOrigEncode) = DefaultJceString;
        JV2_PROP(sDirectDomain) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sPageOrigEncode) = nil;
    JV2_PROP(sDirectDomain) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.RelayPageRsp";
}

@end
