// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSTSingleMD5.h"

@implementation MttSTSingleMD5

@synthesize JV2_PROP_NM(o,0,vSingleMD5);

+ (void)initialize
{
    if (self == [MttSTSingleMD5 class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vSingleMD5) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.STSingleMD5";
}

@end
