// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSTJSInfo.h"

@implementation MttSTJSInfo

@synthesize JV2_PROP_NM(r,0,cJSEvent);
@synthesize JV2_PROP_NM(r,1,iJSQD);
@synthesize JV2_PROP_EX(r,2,vSTPDInfo,VOMTTSTJSPDInfo);

+ (void)initialize
{
    if (self == [MttSTJSInfo class]) {
        [MttSTJSPDInfo initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vSTPDInfo) = DefaultJceArray;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vSTPDInfo) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.STJSInfo";
}

@end
