// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSTStat.h"

@implementation MttSTStat

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,stTime);
@synthesize JV2_PROP_EX(r,2,stTotal,VOMTTSTTotal);
@synthesize JV2_PROP_EX(r,3,stOuterPv,VOMTTSTPV);
@synthesize JV2_PROP_EX(r,4,stInnerPv,VOMTTSTPV);
@synthesize JV2_PROP_NM(r,5,iUseTime);
@synthesize JV2_PROP_EX(o,6,vEntryPv,VOMTTETPV);
@synthesize JV2_PROP_EX(o,7,vFastKey,VOMTTFKINFO);
@synthesize JV2_PROP_NM(o,8,sProtocol);
@synthesize JV2_PROP_EX(o,9,vThirdUse,VOMTTThirdUse);
@synthesize JV2_PROP_EX(o,10,vPerformanceInfo,VOMTTPerformanceInfo);
@synthesize JV2_PROP_EX(o,11,vUseTime,VONSNumber);

+ (void)initialize
{
    if (self == [MttSTStat class]) {
        [MttETPV initialize];
        [MttFKINFO initialize];
        [MttPerformanceInfo initialize];
        [MttSTPV initialize];
        [MttSTTime initialize];
        [MttSTTotal initialize];
        [MttThirdUse initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(stTime) = [MttSTTime object];
        JV2_PROP(stTotal) = DefaultJceArray;
        JV2_PROP(stOuterPv) = DefaultJceArray;
        JV2_PROP(stInnerPv) = DefaultJceArray;
        JV2_PROP(sProtocol) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(stTime) = nil;
    JV2_PROP(stTotal) = nil;
    JV2_PROP(stOuterPv) = nil;
    JV2_PROP(stInnerPv) = nil;
    JV2_PROP(vEntryPv) = nil;
    JV2_PROP(vFastKey) = nil;
    JV2_PROP(sProtocol) = nil;
    JV2_PROP(vThirdUse) = nil;
    JV2_PROP(vPerformanceInfo) = nil;
    JV2_PROP(vUseTime) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.STStat";
}

@end
