// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface MttSTTotal : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sAPN,setSAPN:)) NSString* JV2_PROP_NM(r,0,sAPN);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWapPV,setIWapPV:)) JceInt32 JV2_PROP_NM(r,1,iWapPV);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWebPV,setIWebPV:)) JceInt32 JV2_PROP_NM(r,2,iWebPV);
@property (nonatomic, assign, JV2_PROP_GS_V2(iResPv,setIResPv:)) JceInt32 JV2_PROP_NM(r,3,iResPv);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWapFlow,setIWapFlow:)) JceInt32 JV2_PROP_NM(r,4,iWapFlow);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWebFlow,setIWebFlow:)) JceInt32 JV2_PROP_NM(r,5,iWebFlow);
@property (nonatomic, assign, JV2_PROP_GS_V2(iResFlow,setIResFlow:)) JceInt32 JV2_PROP_NM(r,6,iResFlow);
@property (nonatomic, assign, JV2_PROP_GS_V2(iErrorPV,setIErrorPV:)) JceInt32 JV2_PROP_NM(o,7,iErrorPV);

@end
