// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "MttSplashReq.h"

@implementation MttSplashReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,iWidth);
@synthesize JV2_PROP_NM(r,2,iHeight);
@synthesize JV2_PROP_NM(r,3,sPicMd5);
@synthesize JV2_PROP_NM(r,4,sCondMd5);
@synthesize JV2_PROP_NM(o,5,iVer);

+ (void)initialize
{
    if (self == [MttSplashReq class]) {
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(sPicMd5) = DefaultJceString;
        JV2_PROP(sCondMd5) = DefaultJceString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(sPicMd5) = nil;
    JV2_PROP(sCondMd5) = nil;
    [super dealloc];
}

+ (NSString*)jceType
{
    return @"MTT.SplashReq";
}

@end
