// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/renjunyi/MTT.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    MttStatValue_ENTRY = 1,
    MttStatValue_FASTKEY = 2,
    MttStatValue_DOMAINPV = 4,
    MttStatValue_STATURL = 8,
    MttStatValue_SACTION = 16,
    MttStatValue_THIRDUSE = 32,
    MttStatValue_PERFORMANCE = 64
};
#define MttStatValue NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttStatValueHelper: JceEnumHelper

+ (NSString *)etos:(MttStatValue)e;
+ (MttStatValue)stoe:(NSString *)s;

@end

#endif
