// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.6.3 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/TestServant.jce'
// **********************************************************************

package com.qq.java.testserver.testservant;

import com.qq.taf.server.JceCurrent;

public interface ITestServant
{

    public int testHello(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r, JceCurrent __jc);



    public void testVoid(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r, JceCurrent __jc);


}
