// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.6.3 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/TestServant.jce'
// **********************************************************************

package com.qq.java.testserver.testservant;

public interface TestServantPrx
{
    public int testHello(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r);

    public int testHello(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r, java.util.Map __ctx);

    public void async_testHello(com.qq.java.testserver.testservant.TestServantPrxCallback callback, String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send);

    public void async_testHello(com.qq.java.testserver.testservant.TestServantPrxCallback callback, String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, java.util.Map __ctx);


    public void testVoid(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r);

    public void testVoid(String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, com.qq.taf.holder.JceStringHolder r, java.util.Map __ctx);

    public void async_testVoid(com.qq.java.testserver.testservant.TestServantPrxCallback callback, String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send);

    public void async_testVoid(com.qq.java.testserver.testservant.TestServantPrxCallback callback, String s, int i, long l, boolean b, byte c, byte [] vt, java.util.Map<String, String> mp, com.qq.java.testserver.testservant.Send send, java.util.Map __ctx);


}
