
#-----------------------------------------------------------------------

APP       := Test
TARGET    := TafCaseServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   += -I/usr/local/mqq/wbl/include 
LIB       += -L/usr/local/mqq/wbl/lib -lwbl

#-----------------------------------------------------------------------

TAF_PATH:=/home/kevintian/dev_taf
include ${TAF_PATH}/makefile.taf

#-----------------------------------------------------------------------
