// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Config.jce'
// **********************************************************************

package com.qq.taf;

public final class ConfigInfoHolder
{
    public ConfigInfoHolder()
    {
    }
    public ConfigInfoHolder(ConfigInfo value)
    {
        this.value = value;
    }

    public ConfigInfo value;
}
