// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Config.jce'
// **********************************************************************

package com.qq.taf;

public interface ConfigPrx
{
    public int ListConfig(String app, String server, com.qq.taf.holder.JceArrayListHolder vf);

    public int ListConfig(String app, String server, com.qq.taf.holder.JceArrayListHolder vf, java.util.Map __ctx);

    public void async_ListConfig(com.qq.taf.ConfigPrxCallback callback, String app, String server);

    public void async_ListConfig(com.qq.taf.ConfigPrxCallback callback, String app, String server, java.util.Map __ctx);


    public int ListConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceArrayListHolder vf);

    public int ListConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceArrayListHolder vf, java.util.Map __ctx);

    public void async_ListConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo);

    public void async_ListConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo, java.util.Map __ctx);


    public int checkConfig(String appServerName, String filename, String host, com.qq.taf.holder.JceStringHolder result);

    public int checkConfig(String appServerName, String filename, String host, com.qq.taf.holder.JceStringHolder result, java.util.Map __ctx);

    public void async_checkConfig(com.qq.taf.ConfigPrxCallback callback, String appServerName, String filename, String host);

    public void async_checkConfig(com.qq.taf.ConfigPrxCallback callback, String appServerName, String filename, String host, java.util.Map __ctx);


    public int checkConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceStringHolder result);

    public int checkConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceStringHolder result, java.util.Map __ctx);

    public void async_checkConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo);

    public void async_checkConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo, java.util.Map __ctx);


    public int loadConfig(String app, String server, String filename, com.qq.taf.holder.JceStringHolder config);

    public int loadConfig(String app, String server, String filename, com.qq.taf.holder.JceStringHolder config, java.util.Map __ctx);

    public void async_loadConfig(com.qq.taf.ConfigPrxCallback callback, String app, String server, String filename);

    public void async_loadConfig(com.qq.taf.ConfigPrxCallback callback, String app, String server, String filename, java.util.Map __ctx);


    public int loadConfigByHost(String appServerName, String filename, String host, com.qq.taf.holder.JceStringHolder config);

    public int loadConfigByHost(String appServerName, String filename, String host, com.qq.taf.holder.JceStringHolder config, java.util.Map __ctx);

    public void async_loadConfigByHost(com.qq.taf.ConfigPrxCallback callback, String appServerName, String filename, String host);

    public void async_loadConfigByHost(com.qq.taf.ConfigPrxCallback callback, String appServerName, String filename, String host, java.util.Map __ctx);


    public int loadConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceStringHolder config);

    public int loadConfigByInfo(com.qq.taf.ConfigInfo configInfo, com.qq.taf.holder.JceStringHolder config, java.util.Map __ctx);

    public void async_loadConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo);

    public void async_loadConfigByInfo(com.qq.taf.ConfigPrxCallback callback, com.qq.taf.ConfigInfo configInfo, java.util.Map __ctx);


}
