
#-----------------------------------------------------------------------

APP       := Test
TARGET    := AServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   += -I/usr/local/mqq/wbl/include 
LIB       += -L/usr/local/mqq/wbl/lib -lwbl

#-----------------------------------------------------------------------

include /home/joeyzhong/taf/makefile.taf
#include /usr/local/taf/makefile.taf
#include /usr/local/taf-version/taf-1.6.4/makefile.taf

#-----------------------------------------------------------------------
