
#-----------------------------------------------------------------------

APP       := Test
TARGET    := BServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   +=
LIB       +=

#-----------------------------------------------------------------------

include /home/tafjce/Test/AServer/AServer.mk
include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
