// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.6.1 by WSRD Tencent.
// Generated from `QueryF.jce'
// **********************************************************************

package com.duowan.taf;

public interface QueryFPrx
{
    public java.util.ArrayList<com.duowan.taf.EndpointF> findObjectById(String id);

    public java.util.ArrayList<com.duowan.taf.EndpointF> findObjectById(String id, java.util.Map __ctx);

    public void async_findObjectById(com.duowan.taf.QueryFPrxCallback callback, String id);

    public void async_findObjectById(com.duowan.taf.QueryFPrxCallback callback, String id, java.util.Map __ctx);


    public int findObjectById4All(String id, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp);

    public int findObjectById4All(String id, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp, java.util.Map __ctx);

    public void async_findObjectById4All(com.duowan.taf.QueryFPrxCallback callback, String id);

    public void async_findObjectById4All(com.duowan.taf.QueryFPrxCallback callback, String id, java.util.Map __ctx);


    public int findObjectByIdInSameGroup(String id, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp);

    public int findObjectByIdInSameGroup(String id, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp, java.util.Map __ctx);

    public void async_findObjectByIdInSameGroup(com.duowan.taf.QueryFPrxCallback callback, String id);

    public void async_findObjectByIdInSameGroup(com.duowan.taf.QueryFPrxCallback callback, String id, java.util.Map __ctx);


    public int findObjectByIdInSameStation(String id, String sStation, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp);

    public int findObjectByIdInSameStation(String id, String sStation, com.duowan.taf.holder.JceArrayListHolder activeEp, com.duowan.taf.holder.JceArrayListHolder inactiveEp, java.util.Map __ctx);

    public void async_findObjectByIdInSameStation(com.duowan.taf.QueryFPrxCallback callback, String id, String sStation);

    public void async_findObjectByIdInSameStation(com.duowan.taf.QueryFPrxCallback callback, String id, String sStation, java.util.Map __ctx);


}
