// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.0.1 by WSRD Tencent.
// Generated from `StatF.jce'
// **********************************************************************

package com.qq.taf;

public final class StatMicMsgHeadHolder
{
    public StatMicMsgHeadHolder()
    {
    }
    public StatMicMsgHeadHolder(StatMicMsgHead value)
    {
        this.value = value;
    }

    public StatMicMsgHead value;
}
