
TOPDIR	:= ../..
include ${TOPDIR}/make.rules

#--------------------------------------------------------

INCLUDE += 
LIB     += -lhessian -lutil 

#--------------------------------------------------------

TARGET := TestHce2Cpp

#--------------------------------------------------------

include ${TOPDIR}/inc.mk

