// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.5.7 by WSRD Tencent.
// Generated from `test.jce'
// **********************************************************************

package com.qq.java.test;

public final class BrokerDisplayInfo extends com.qq.taf.jce.JceStruct
{
    public String className()
    {
        return "test.BrokerDisplayInfo";
    }

    public short wScreenWidth = 12;

    public short wScreenHeight = 320;

    public byte cFontSize = 14;

    public byte cRowSpacing = 1;

    public byte [] vCharSetKey = null;

    public short getWScreenWidth()
    {
        return wScreenWidth;
    }

    public void  setWScreenWidth(short wScreenWidth)
    {
        this.wScreenWidth = wScreenWidth;
    }

    public short getWScreenHeight()
    {
        return wScreenHeight;
    }

    public void  setWScreenHeight(short wScreenHeight)
    {
        this.wScreenHeight = wScreenHeight;
    }

    public byte getCFontSize()
    {
        return cFontSize;
    }

    public void  setCFontSize(byte cFontSize)
    {
        this.cFontSize = cFontSize;
    }

    public byte getCRowSpacing()
    {
        return cRowSpacing;
    }

    public void  setCRowSpacing(byte cRowSpacing)
    {
        this.cRowSpacing = cRowSpacing;
    }

    public byte [] getVCharSetKey()
    {
        return vCharSetKey;
    }

    public void  setVCharSetKey(byte [] vCharSetKey)
    {
        this.vCharSetKey = vCharSetKey;
    }

    public BrokerDisplayInfo()
    {
        setWScreenWidth(wScreenWidth);
        setWScreenHeight(wScreenHeight);
        setCFontSize(cFontSize);
        setCRowSpacing(cRowSpacing);
        setVCharSetKey(vCharSetKey);
    }

    public BrokerDisplayInfo(short wScreenWidth, short wScreenHeight, byte cFontSize, byte cRowSpacing, byte [] vCharSetKey)
    {
        setWScreenWidth(wScreenWidth);
        setWScreenHeight(wScreenHeight);
        setCFontSize(cFontSize);
        setCRowSpacing(cRowSpacing);
        setVCharSetKey(vCharSetKey);
    }

    public boolean equals(Object o)
    {
        BrokerDisplayInfo t = (BrokerDisplayInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(wScreenWidth, t.wScreenWidth) && 
            com.qq.taf.jce.JceUtil.equals(wScreenHeight, t.wScreenHeight) && 
            com.qq.taf.jce.JceUtil.equals(cFontSize, t.cFontSize) && 
            com.qq.taf.jce.JceUtil.equals(cRowSpacing, t.cRowSpacing) && 
            com.qq.taf.jce.JceUtil.equals(vCharSetKey, t.vCharSetKey) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (wScreenWidth != 12)
        {
            _os.write(wScreenWidth, 0);
        }
        if (wScreenHeight != 320)
        {
            _os.write(wScreenHeight, 1);
        }
        if (cFontSize != 14)
        {
            _os.write(cFontSize, 2);
        }
        if (cRowSpacing != 1)
        {
            _os.write(cRowSpacing, 3);
        }
        if (null != vCharSetKey)
        {
            _os.write(vCharSetKey, 4);
        }
    }

    static byte [] cache_vCharSetKey;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setWScreenWidth((short) _is.read(wScreenWidth, 0, false));

        setWScreenHeight((short) _is.read(wScreenHeight, 1, false));

        setCFontSize((byte) _is.read(cFontSize, 2, false));

        setCRowSpacing((byte) _is.read(cRowSpacing, 3, false));

        if(null == cache_vCharSetKey)
        {
            cache_vCharSetKey = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vCharSetKey)[0] = __var_1;
        }
        setVCharSetKey((byte []) _is.read(cache_vCharSetKey, 4, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(wScreenWidth, "wScreenWidth");
        _ds.display(wScreenHeight, "wScreenHeight");
        _ds.display(cFontSize, "cFontSize");
        _ds.display(cRowSpacing, "cRowSpacing");
        _ds.display(vCharSetKey, "vCharSetKey");
    }

}

